from pathlib import Path
from html import escape
import json
OUT=Path(__file__).parent/'dist'
LANG='fr'
PHOTO_SIZES={f"ancien-{v['id']:02}":(v['width'],v['height']) for v in json.loads((Path(__file__).parent/'photo-sources.json').read_text())}
def t(fr,en): return fr if LANG=='fr' else en
routes={'home':('',''), 'particuliers':('demenagement-particuliers','home-moving'),'entreprises':('demenagement-entreprises','office-moving'),'europe':('france-europe','france-europe'),'stockage':('garde-meubles','storage'),'monte':('monte-meubles','furniture-lift'),'piano':('objets-specialises','specialist-items'),'formules':('formules','moving-options'),'zones':('zones-desservies','areas-covered'),'apropos':('a-propos','about'),'conseils':('conseils','moving-advice'),'contact':('contact','contact'),'devis':('devis','quote'),'legal':('mentions-legales','legal-notice'),'privacy':('confidentialite','privacy'),'cookies':('cookies','cookies'),'access':('accessibilite','accessibility'),'avis':('avis-clients','reviews'),'realisations':('realisations','case-studies')}
labels={'home':('Accueil','Home'),'particuliers':('Particuliers','Home moves'),'entreprises':('Entreprises','Business moves'),'europe':('France & Europe','France & Europe'),'stockage':('Garde-meubles','Storage'),'monte':('Monte-meubles','Furniture lift'),'piano':('Objets spécialisés','Specialist items'),'formules':('Nos formules','Moving options'),'zones':('Zones desservies','Areas covered'),'apropos':('À propos','About CODEM'),'conseils':('Conseils','Moving advice'),'contact':('Contact','Contact'),'devis':('Demander un devis','Request a quote'),'legal':('Mentions légales','Legal notice'),'privacy':('Confidentialité','Privacy'),'cookies':('Cookies','Cookies'),'access':('Accessibilité','Accessibility'),'avis':('Avis clients','Client reviews'),'realisations':('Réalisations','Case studies')}
PHONE='01 71 36 18 38';PHONE_HREF='tel:+33171361838'
def label(k):return t(*labels[k])
def url(k,lang=None):
 l=lang or LANG;s=routes[k][0 if l=='fr' else 1];return '/'+l+'/'+(s+'/' if s else '')
def link(k,txt=None,cls='',extra=''):return f'<a href="{url(k)}" class="{cls}" {extra}>{txt or label(k)}</a>'
def img(name,alt='',cls='',eager=False):
 w,h=PHOTO_SIZES.get(name,(1280,853))
 return f'<img class="{cls}" src="/assets/{name}-1280.webp" srcset="/assets/{name}-640.webp 640w, /assets/{name}-1280.webp 1280w" sizes="(max-width:640px) 90vw, 50vw" width="{w}" height="{h}" alt="{escape(alt)}" loading="{"eager" if eager else "lazy"}" decoding="async">'

def video(name,hero=False):return f'<video data-video="{name}" data-src="/assets/{name}.mp4" poster="/assets/{name}-poster.jpg" muted loop playsinline preload="none" aria-label="{t("Scène animée illustrant les services CODEM","Animated illustration of CODEM moving services")}"></video>'
def toggle():return f'<button class="video-toggle" type="button" data-video-toggle aria-pressed="false">{t("Lire la vidéo","Play video")}</button>'
def eyebrow(a,b):return '<span class="eyebrow">'+t(a,b)+'</span>'
def actions():return f'<div class="actions">{link("devis",t("Décrire mon projet","Tell us about your move"),"btn")}{link("contact",t("Parlons-en","Let’s talk"),"text-link")}</div>'
def header(key):
 nav=''.join(link(k,extra='aria-current="page"' if k==key else '') for k in ['home','particuliers','entreprises','formules','zones','contact'])
 more=''.join(link(k) for k in ['europe','stockage','monte','piano','apropos','conseils','avis','realisations'])
 return f'''<a href="#main" class="skip">{t('Aller au contenu','Skip to content')}</a><header><div class="header-inner"><a class="brand" href="{url('home')}" aria-label="CODEM — {label('home')}"><img src="/assets/logo-codem.png" width="1200" height="582" alt="CODEM"></a><nav class="desktop-nav" aria-label="{t('Navigation principale','Main navigation')}">{nav}</nav><div class="header-actions"><div class="lang" aria-label="{t('Langue','Language')}"><a href="{url(key,'fr')}" lang="fr" aria-current="{str(LANG=='fr').lower()}">FR</a><span>/</span><a href="{url(key,'en')}" lang="en" aria-current="{str(LANG=='en').lower()}">EN</a></div><a class="header-phone" href="{PHONE_HREF}">{PHONE}</a>{link('contact',t('Être rappelé','Callback'),'btn outline btn-callback','data-callback')}{link('devis',t('Demander un devis','Get a quote'),'btn btn-cta')}<button type="button" class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu">Menu</button></div></div><nav id="mobile-menu" class="mobile-menu" hidden aria-label="{t('Navigation mobile','Mobile navigation')}">{nav}{more}{link('devis',t('Demander un devis','Get a quote'),'btn btn-cta')}</nav></header>'''
def footer():
 def group(title,keys):return '<div><h3>'+title+'</h3>'+''.join(link(k) for k in keys)+'</div>'
 return f'''<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a href="{url('home')}"><img class="footer-logo" src="/assets/logo-codem.png" width="1200" height="582" alt="CODEM"></a><p>39 boulevard de Strasbourg<br>94130 Nogent-sur-Marne</p><a href="tel:+33171361838">01 71 36 18 38</a><a href="tel:+33667570912">06 67 57 09 12</a><p class="footer-hours">{t('Lun – jeu 9 h – 18 h · ven. jusqu’à 17 h','Mon – Thu 9 am – 6 pm · Fri until 5 pm')}</p>{link('devis',t('Demander un devis','Get a quote'),'btn btn-cta')}</div>{group(t('Nos services','Our services'),['particuliers','entreprises','europe','stockage','monte','piano'])}{group(t('Informations','Information'),['formules','zones','apropos','conseils','avis','realisations','contact'])}{group(t('Cadre légal','Legal'),['legal','privacy','cookies','access'])}</div><div class="footer-bottom"><p>© 2026 CODEM · {t('Déménagements & garde-meubles','Moving & storage')}</p><button type="button" data-cookie-open>{t('Préférences de confidentialité','Privacy preferences')}</button></div></div></footer><div class="mobile-bottom"><a class="mb-call" href="tel:+33171361838">{t('Appeler','Call')}</a><a class="mb-callback" href="{url('contact')}#rappel">{t('Rappel','Callback')}</a><a class="mb-quote" href="{url('devis')}">{t('Devis','Quote')}</a></div><dialog class="cookie-dialog" id="cookie-dialog"><h2>{t('Votre vie privée.','Your privacy.')}</h2><p>{t('Ce site n’utilise actuellement aucun traceur publicitaire ni outil de mesure d’audience. Votre choix est conservé uniquement dans ce navigateur.','This site currently uses no advertising trackers or audience analytics. Your choice is saved only in this browser.')}</p><div class="actions"><button class="btn outline" data-cookie-choice="refused">{t('Tout refuser','Reject all')}</button><button class="btn" data-cookie-choice="accepted">{t('Tout accepter','Accept all')}</button><button class="text-link" data-cookie-close>{t('Fermer','Close')}</button></div></dialog>'''
def cta(title=None):return f'<section class="cta band-cta"><div class="wrap"><div><span class="eyebrow">{t("Devis gratuit · réponse d’un conseiller","Free quote · reply from an adviser")}</span><h2>{title or t("Parlons de votre<br><em>prochain départ.</em>","Let’s talk about<br><em>your next chapter.</em>")}</h2></div><div class="actions">{link("devis",t("Demander un devis","Request a quote"),"btn btn-cta")}{link("contact",t("Être rappelé","Request a callback"),"btn outline")}<a class="cta-phone" href="{PHONE_HREF}">{PHONE}</a></div></div></section>'
def cta_strip(fr,en,service=None):
 q=url('devis')+(f'?service={service}' if service else '')
 return f'<div class="cta-strip"><div class="wrap"><p>{t(fr,en)}</p><div class="actions"><a class="btn btn-cta" href="{q}">{t("Demander un devis","Get a quote")}</a>{link("contact",t("Être rappelé","Callback"),"btn outline")}</div></div></div>'
def shell(key,body,desc=None,head=''):
 title= t('CODEM — Votre déménagement, l’esprit libre.','CODEM — Moving, with peace of mind.') if key=='home' else label(key)+' | CODEM'
 desc=desc or t('CODEM organise votre déménagement à Paris, en Île-de-France, en France et en Europe. Protection, transport et prestations adaptées à votre projet.','CODEM organises home and office moves in Paris, Greater Paris, France and Europe. Packing, transport and services tailored to your move.')
 return f'''<!doctype html><html lang="{LANG}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(desc)}"><meta name="theme-color" content="#22264f"><link rel="canonical" href="{url(key)}"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:type" content="website"><meta property="og:image" content="/assets/ancien-03-1280.webp"><link rel="alternate" hreflang="fr" href="{url(key,'fr')}"><link rel="alternate" hreflang="en" href="{url(key,'en')}"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%232c2f77'/%3E%3Ctext x='16' y='24' text-anchor='middle' font-family='Georgia' font-size='26' fill='white'%3EC%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/premium.css"><link rel="stylesheet" href="/assets/brand.css"><link rel="stylesheet" href="/assets/motion.css"><link rel="stylesheet" href="/assets/tools.css">{head}<script src="/assets/site.js" defer></script><script src="/assets/motion.js" defer></script><script src="/assets/tools.js" defer></script></head><body class="{'home-page' if key=='home' else 'form-page' if key in ['devis','contact'] else 'inner-page'}">{header(key)}<main id="main">{body}</main>{footer()}</body></html>'''
def steps(part=False):
 data=[('Décrivez votre trajet','Tell us about your move','Départ, arrivée, période et type de logement : posons les bases de votre projet.','Tell us where you are moving from and to, your preferred dates and property type.'),('Choisissez les prestations','Choose your services','Cartons, emballage, démontage, protection et remise en place : précisez ce que vous souhaitez nous confier.','Boxes, packing, dismantling, protection and placement: choose what you would like us to handle.'),('Étudions le volume et les accès','Review volume and access','CODEM étudie vos informations et prévoit une visite si nécessaire avant de vous proposer une solution.','CODEM reviews your information and arranges a visit if needed before recommending a solution.')]
 if not part:data=[('Votre projet','Your move','Vous nous décrivez votre besoin, votre trajet et la période envisagée.','Tell us about your needs, your route and preferred dates.'),('L’étude & le devis','Assessment & quote','Nous examinons le volume et les accès pour établir une proposition adaptée.','We assess volume and access to prepare a tailored proposal.'),('La préparation','Preparation','Emballages, protection, moyens de manutention : chaque prestation est précisée.','Packing materials, protection and handling equipment: each service is agreed.'),('Le jour du départ','Moving day','Les prestations convenues sont coordonnées jusqu’à la remise en place à destination.','Your agreed services are coordinated through to placement at your destination.')]
 return '<div class="process"'+(' style="grid-template-columns:repeat(3,1fr)"' if part else '')+'>'+''.join(f'<article class="reveal"><span class="number">0{i+1}</span><h3>{t(a,b)}</h3><p>{t(c,d)}</p></article>' for i,(a,b,c,d) in enumerate(data))+'</div>'
def faq_rows(extra=False):
 data=[('Je ne connais pas mon volume. Comment faire ?','I don’t know my moving volume. What should I do ?','Indiquez la surface, le nombre de pièces et les principaux meubles. Vous pouvez choisir « Je ne sais pas » dans le devis. CODEM étudiera le volume avec vous.','Share your floor area, number of rooms and main furniture items. Select “I don’t know” in the quote form if needed. CODEM will assess the volume with you.'),('Et si les accès sont compliqués ?','What if access is difficult ?','Précisez les étages, l’ascenseur, les escaliers et le stationnement. Les moyens adaptés, dont le monte-meubles, sont étudiés selon la configuration et les autorisations nécessaires.','Tell us about floors, lifts, stairs and parking. Suitable equipment, including a furniture lift, is assessed against access conditions and any necessary permissions.'),('Pouvez-vous emballer les objets fragiles ?','Can you pack fragile items ?','La vaisselle, les tableaux, les miroirs et les équipements sensibles peuvent bénéficier de protections adaptées selon la prestation convenue. Signalez vos objets particuliers dès le premier échange.','Dishes, artwork, mirrors and sensitive equipment can receive suitable protection as part of the agreed service. Mention any specialist items when you first contact us.'),('L’emballage et le déballage sont-ils inclus ?','Are packing and unpacking included ?','Cela dépend de la formule et des prestations retenues. Le devis précise ce qui est pris en charge par CODEM et ce que vous préparez vous-même.','This depends on the selected package and services. Your quote specifies what CODEM handles and what you prepare yourself.'),('Puis-je prévoir une période de garde-meubles ?','Can I arrange temporary storage ?','Oui, signalez le volume à entreposer et la durée souhaitée. Les conditions de stockage, de dépôt et de restitution sont précisées avec CODEM.','Yes. Tell us the volume you need to store and the intended duration. Storage, collection and return arrangements are agreed with CODEM.'),('Quelles destinations desservez-vous ?','Which destinations do you serve ?','Paris, l’Île-de-France, la France et des destinations européennes, notamment l’Espagne, le Portugal et l’Italie. Chaque trajet est étudié selon la destination, les volumes et les accès.','Paris, Greater Paris, France and European destinations including Spain, Portugal and Italy. Each route is assessed according to destination, volume and access.')]
 if extra:data=[('Le formulaire donne-t-il un prix ?','Does the form give a price?','Non. Il prépare une demande structurée. Toute proposition commerciale est établie par un conseiller après vérification des informations.','No. It prepares a structured request. Any proposal is prepared by an adviser after checking the details.'),('Puis-je revenir à une étape précédente ?','Can I go back to a previous step?','Oui. Vos réponses restent conservées sur le même appareil pendant la préparation de la demande.','Yes. Your answers are kept on the same device while you prepare your request.'),('Dois-je saisir mon adresse exacte ?','Do I need my exact address?','Non. Une commune suffit pour commencer ; l’adresse précise pourra être ajoutée ensuite.','No. A town is enough to start; the exact address can be added later.')]+data
 return [(t(a,b),t(c,d)) for a,b,c,d in data]
def FAQ_DATA():return faq_rows(True)
def faqs(extra=False):return ''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in faq_rows(extra))
def service_showcase():
 data=[('particuliers','ancien-07','Un nouveau lieu. Le même sentiment d’être chez soi.','A new place. The same feeling of home.','Du premier carton à votre installation, choisissons les prestations qui vous simplifient la vie.','From the first box to settling in, choose the services that make your move easier.'),('entreprises','ancien-08','Votre activité change d’adresse.','Your business is moving forward.','Mobilier, postes de travail et équipements : un transfert préparé autour de votre activité.','Furniture, workstations and equipment: a relocation planned around your business.'),('europe','ancien-06','Plus loin, avec la même attention.','Further afield, with the same care.','Paris, la France et l’Europe. Un trajet organisé selon votre destination et vos contraintes.','Paris, France and Europe. A journey planned around your destination and requirements.'),('piano','ancien-28','Ce qui compte mérite du soin.','What matters deserves care.','Pianos, tableaux et objets fragiles : des protections étudiées, des gestes précis.','Pianos, artwork and fragile belongings: considered protection and careful handling.'),('stockage','stockage','De la place pour la suite.','Make room for what’s next.','Entre deux adresses ou pour plus longtemps, une solution adaptée au volume à entreposer.','Between homes or for longer, a solution suited to the volume you need to store.'),('monte','monte-meubles','Un autre chemin jusqu’à chez vous.','Another way to reach your home.','Un équipement pour les étages, après étude des accès et des autorisations nécessaires.','Equipment for upper floors, following an assessment of access and required permissions.')]
 rows=[];visuals=[]
 for i,(k,im,a,b,c,d) in enumerate(data):
  rows.append(f'<div class="expertise-item"><h3><button type="button" class="expertise-trigger" aria-expanded="{str(i==0).lower()}" aria-controls="expertise-{i}" data-service-index="{i}"><span class="index">0{i+1}</span><span>{label(k)}</span><span class="plus" aria-hidden="true">+</span></button></h3><div class="expertise-panel" id="expertise-{i}" {"hidden" if i else ""}><p>{t(c,d)}</p>{link(k,t("Découvrir ce service","Explore this service"),"text-link")}</div></div>')
  arrow=link(k,"↗","circle-link",'aria-label="'+label(k)+'"')
  visuals.append(f'<figure class="expertise-visual" data-service-visual="{i}" {"hidden" if i else ""}>{img(im,label(k))}<figcaption><span>{t(a,b)}</span>{arrow}</figcaption></figure>')
 return '<div class="expertise-layout reveal"><div class="expertise-list">'+''.join(rows)+'</div><div class="expertise-visuals">'+''.join(visuals)+'</div></div>'

def quickstart():
 opt=lambda v,fr,en:f'<option value="{v}">{t(fr,en)}</option>'
 logement=opt('','Logement','Property')+opt('appartement','Appartement','Flat')+opt('maison','Maison','House')+opt('bureaux','Bureaux ou local','Office')+opt('stockage','Stockage','Storage')+opt('autre','Autre','Other')
 acces=opt('','Accès','Access')+opt('ascenseur','Avec ascenseur','With lift')+opt('escalier','Escalier uniquement','Stairs only')+opt('monte-meubles','Monte-meubles à prévoir','Furniture lift needed')+opt('a-verifier','À vérifier','To check')
 taille=opt('','Volume','Volume')+opt('studio','Studio / T1','Studio / 1 room')+opt('t2-t3','T2 – T3','2 – 3 rooms')+opt('t4','T4 et plus','4+ rooms')+opt('maison','Maison','House')+opt('inconnu','Je ne sais pas','I don’t know')
 return f'''<section class="quickstart band-ivory" aria-labelledby="qs-title"><div class="wrap qs-grid"><div class="qs-intro"><span class="eyebrow">{t('Votre projet en quelques étapes','Your move in a few steps')}</span><h2 id="qs-title">{t('Un trajet clair,<br><em>une demande mieux préparée.</em>','A clear route,<br><em>a better-prepared request.</em>')}</h2><p class="subtle">{t('Indiquez l’essentiel maintenant. Vous pourrez compléter et modifier chaque réponse avant l’envoi.','Enter the essentials now. You can complete and edit every answer before sending.')}</p></div><form class="qs-form" action="{url('devis')}" method="get"><div class="qs-route"><label class="qs-point"><span class="qs-badge">A</span><span><small>{t('Départ','From')}</small><input name="depart" placeholder="{t('Votre commune','Your town')}" aria-label="{t('Commune de départ','Collection town')}" autocomplete="address-level2"></span></label><span class="qs-line" aria-hidden="true"></span><label class="qs-point"><span class="qs-badge b">B</span><span><small>{t('Arrivée','To')}</small><input name="arrivee" placeholder="{t('Votre destination','Your destination')}" aria-label="{t('Destination','Destination')}"></span></label></div><div class="qs-fields"><input type="date" name="date" aria-label="{t('Date souhaitée','Preferred date')}" data-min-today><select name="logement" aria-label="{t('Type de logement','Property type')}">{logement}</select><select name="acces" aria-label="{t('Accès','Access')}">{acces}</select><select name="taille" aria-label="{t('Volume','Volume')}">{taille}</select></div><button class="btn btn-cta btn-block" type="submit">{t('Commencer ma demande','Start my request')}</button></form></div></section>'''
def services_band():
 return '<nav class="services-band" aria-label="'+t('Nos services','Our services')+'"><div class="wrap">'+''.join(link(k) for k in ['particuliers','entreprises','europe','stockage','monte','piano'])+'</div></nav>'
def pillars():
 data=[('particuliers','Déménagement sur mesure','Tailored moves','Véhicules capitonnés, protection du mobilier et cinq formules pour répartir les tâches selon vos besoins.','Padded vehicles, furniture protection and five packages to share tasks the way you want.','Voir les prestations','See the services'),('stockage','Stockage de vos biens','Storing your belongings','Solutions de garde-meubles pour le mobilier, les affaires personnelles ou les archives, sur une courte ou longue durée.','Storage for furniture, personal belongings or records, short or long term.','Découvrir le garde-meubles','Explore storage'),('piano','Manutention spécialisée','Specialist handling','Protections adaptées, emballage sur mesure et moyens techniques pour les objets fragiles, précieux, lourds ou volumineux.','Suitable protection, custom packing and technical equipment for fragile, valuable, heavy or bulky items.','Protéger mes objets','Protect my items')]
 cards=''.join(f'<article class="pillar reveal"><span class="pillar-num">0{i+1}</span><h3>{t(a,b)}</h3><p>{t(c,d)}</p>{link(k,t(e,f)+" →","text-link")}</article>' for i,(k,a,b,c,d,e,f) in enumerate(data))
 return f'<section class="section band-glacier"><div class="wrap"><div class="section-heading"><div>{eyebrow("Le savoir-faire CODEM","CODEM expertise")}<h2>{t("Des déménageurs expérimentés<br><em>pour vos projets en France et en Europe.</em>","Experienced movers<br><em>for your moves in France and Europe.</em>")}</h2></div><p class="subtle">{t("Basée à Nogent-sur-Marne, CODEM accompagne les particuliers et les professionnels avec des prestations personnalisées, du premier inventaire jusqu’à la remise en place.","Based in Nogent-sur-Marne, CODEM supports households and businesses with tailored services, from the first inventory to final placement.")}</p></div><div class="pillars">{cards}</div></div></section>'
def zones_block():
 return f'<section class="section band-sand"><div class="wrap split"><div class="zone-visual reveal"><div class="image-wrap">{img("camion-campagne",t("Camion CODEM sur la route","CODEM truck on the road"))}</div><p><strong>{t("Départs dans toute la France","Departures across France")}</strong><br>{t("Chaque trajet est étudié selon votre projet.","Every route is assessed for your move.")}</p></div><div>{eyebrow("Zones desservies","Areas covered")}<h2>{t("Votre trajet peut commencer<br><em>partout en France.</em>","Your move can start<br><em>anywhere in France.</em>")}</h2><p>{t("Basée à Nogent-sur-Marne, l’équipe CODEM étudie les déménagements au départ de l’Île-de-France comme des autres régions, vers la France ou l’Europe.","Based in Nogent-sur-Marne, the CODEM team assesses moves from Greater Paris and other regions, to anywhere in France or Europe.")}</p><p>{t("Italie, Espagne et Portugal font partie des destinations mises en avant. La faisabilité, le groupage et les formalités sont confirmés au cas par cas.","Italy, Spain and Portugal are among our main destinations. Feasibility, shared loads and formalities are confirmed case by case.")}</p><div class="actions">{link("devis",t("Faire vérifier mon trajet","Check my route"),"btn btn-cta")}{link("zones",cls="text-link")}</div></div></div></section>'
def home():
 return f'''<section class="hero">{video('hero-retour-famille',True)}<div class="wrap hero-content">{eyebrow('Déménagements & garde-meubles','Moving & storage')}<h1 class="hero-title" data-titles="{escape(json.dumps([[a,t(b,c)] for a,b,c in [[4.8,'Chaque geste<br><em>compte.</em>','Every move<br><em>matters.</em>'],[9.5,'<em>CODEM vous accompagne.</em>','<em>CODEM is with you.</em>'],[14.2,'<span class="ht-desk">Soyez tranquille.<br></span><em>CODEM s’occupe de tout.</em>','<span class="ht-desk">Relax.<br></span><em>CODEM handles everything.</em>']]],ensure_ascii=False))}">{t('Votre déménagement.<br><em>L’esprit libre.</em>','Your next chapter.<br><em>Peace of mind.</em>')}</h1><p>{t('À Paris, en France et en Europe, CODEM coordonne votre déménagement de A à Z, avec toute l’attention que vos biens méritent.','In Paris, across France and throughout Europe, CODEM coordinates your move from start to finish, with the care your belongings deserve.')}</p><div class="actions">{link('devis',t('Demander un devis gratuit','Get a free quote'),'btn btn-cta btn-lg')}{link('contact',t('Être rappelé','Request a callback'),'text-link')}<a class="hero-phone" href="{PHONE_HREF}">{PHONE}</a></div></div><div class="hero-bottom"><a href="#approche">{t('Découvrez une autre façon de déménager','Discover a more thoughtful way to move')}</a>{toggle()}</div></section><div class="wrap trust-line"><span>{t('Un projet coordonné de A à Z','Your move, coordinated from start to finish')}</span><span>{t('Un conseiller étudie chaque demande','An adviser reviews every request')}</span><span>{t('Devis gratuit, sans engagement','Free quote, no commitment')}</span></div>{quickstart()}{services_band()}
 {pillars()}<section class="section band-ivory" id="approche"><div class="wrap intro-grid reveal"><div>{eyebrow('L’approche CODEM','The CODEM approach')}<h2>{t('Vous imaginez la suite.<br><em class="accent">Nous préparons le départ.</em>','You imagine what’s next.<br><em class="accent">We prepare the move.</em>')}</h2></div><div><p class="lead">{t('Déménager, c’est bien plus que transporter des meubles. C’est confier une part de son quotidien.','Moving is about more than transporting furniture. It means entrusting someone with part of your everyday life.')}</p><p class="subtle">{t('Préparation, emballage, protection, manutention, transport et installation : CODEM réunit les prestations convenues autour d’une organisation claire. Pour un appartement, une maison ou des locaux professionnels, nous partons de votre réalité.','Preparation, packing, protection, handling, transport and installation: CODEM brings your agreed services together in one clear plan. For a flat, a house or a workplace, we start with what matters to you.')}</p>{link('apropos',t('Faire connaissance avec CODEM','Meet CODEM'),'text-link')}</div></div></section>
 <section class="section band-sand"><div class="wrap"><div class="section-heading reveal"><div>{eyebrow('Nos savoir-faire','Our expertise')}<h2>{t('Chaque projet est singulier.<br><em>Notre attention reste la même.</em>','Every move is different.<br><em>Our care stays the same.</em>')}</h2></div></div>{service_showcase()}</div></section>{cta_strip('Un projet en tête ? Décrivez-le en quelques minutes.','Planning a move? Describe it in a few minutes.')}
 <section class="section dark"><div class="wrap split"><div class="reveal">{eyebrow('Tous les intérieurs, la même attention','Every home, the same care')}<h2>{t('Ce n’est pas seulement<br><em>une question d’adresse.</em>','It’s about more<br><em>than an address.</em>')}</h2><p>{t('Un premier appartement, une maison de famille, un intérieur d’exception. Nous accordons le même soin aux biens qui font votre vie.','A first flat, a family home, an exceptional interior. We give the same care to the belongings that make up your life.')}</p><ul class="check-list"><li>{t('Des protections adaptées à vos biens','Protection suited to your belongings')}</li><li>{t('Des accès étudiés avant le déménagement','Access assessed before moving day')}</li><li>{t('Une organisation selon les prestations choisies','A plan built around your selected services')}</li></ul>{link('particuliers',t('Découvrir notre accompagnement','Discover how we help'),'btn light')}</div><div class="layered-media reveal"><div class="image-wrap">{img("ancien-03",t("Camion CODEM prêt au chargement devant une maison","CODEM moving truck outside a house"))}</div><div class="image-wrap detail-image">{img("ancien-14",t("Mobilier ancien à protéger pour le transport","Antique furniture requiring transport protection"))}<span>{t("L’attention, jusque dans les détails.","Care, down to the smallest detail.")}</span></div></div></div></section>
 <section class="section band-ivory"><div class="wrap"><div class="wide-film">{video('route')}<div class="film-copy">{eyebrow('France & Europe','France & Europe')}<h2>{t('Votre horizon change.<br><em>Notre soin vous suit.</em>','New horizons.<br><em>The same care.</em>')}</h2><p>{t('Une autre ville, une autre région, un autre pays. Chaque trajet commence par l’étude de votre destination, de votre volume et de vos accès.','A new city, a new region, a new country. Every journey begins with an assessment of your destination, volume and access.')}</p>{link('europe',t('Préparer mon trajet','Plan my journey'),'btn light')}</div>{toggle()}</div></div></section>
 <section class="section band-glacier"><div class="wrap">{eyebrow('Un déménagement bien préparé','A well-prepared move')}<h2>{t('Un chemin clair.<br><em>Du premier échange à l’arrivée.</em>','A clear path.<br><em>From our first conversation to arrival.</em>')}</h2>{steps()}<div class="actions inset">{link("devis",t("Préparer ma demande","Start my request"),"btn btn-cta")}</div></div></section>
 <section class="section band-ivory"><div class="wrap split"><div class="reveal">{eyebrow('La protection de vos biens','Protecting your belongings')}<h2>{t('Le soin commence<br><em>avant le transport.</em>','Care begins<br><em>before the journey.</em>')}</h2><p>{t('Vaisselle, livres, vêtements sur cintres, télévisions, miroirs, tableaux : les emballages et les protections s’adaptent aux objets. Le démontage, le remontage et la remise en place sont définis selon la prestation choisie.','Dishes, books, hanging clothes, televisions, mirrors and artwork: packing materials and protection are matched to each item. Dismantling, reassembly and placement are defined by your selected service.')}</p>{link('piano',t('Confier un objet particulier','Arrange care for a specialist item'),'text-link')}</div><div class="image-wrap reveal">{img('ancien-27',t('Fermeture d’un carton avec un adhésif fragile','Sealing a moving box with fragile tape'))}</div></div></section>
 <section class="section band-ivory" style="padding-top:0"><div class="wrap"><div class="section-heading"><div>{eyebrow('CODEM, sur le terrain','CODEM in the field')}<h2>{t('Des moyens concrets.<br><em>Une présence à vos côtés.</em>','Practical resources.<br><em>People by your side.</em>')}</h2></div></div><div class="real-grid"><figure class="no-margin">{img('ancien-02',t('Véhicules CODEM lors d’une intervention','CODEM vehicles during a move'))}<figcaption class="caption">{t('Les véhicules CODEM.','CODEM vehicles.')}</figcaption></figure><figure class="no-margin">{img('ancien-21',t('Monte-meubles CODEM installé devant une maison','CODEM furniture lift positioned outside a house'))}<figcaption class="caption">{t('Un monte-meubles en intervention — moyens soumis à l’étude des accès.','A furniture lift in use — equipment subject to access assessment.')}</figcaption></figure></div></div></section>{zones_block()}
 <section class="section band-glacier"><div class="wrap faq-grid"><div>{eyebrow('Avant de faire vos cartons','Before you start packing')}<h2>{t('Quelques réponses.<br><em>Pour avancer sereinement.</em>','A few answers.<br><em>For a smoother start.</em>')}</h2>{link('contact',t('Une autre question ? Parlons-en.','Another question? Let’s talk.'),'text-link')}</div><div>{faqs(True)}</div></div></section>{cta()}'''
def home_jsonld():
 data={"@context":"https://schema.org","@graph":[{"@type":"MovingCompany","name":"CODEM Déménagements","telephone":["+33171361838","+33667570912"],"address":{"@type":"PostalAddress","streetAddress":"39 boulevard de Strasbourg","postalCode":"94130","addressLocality":"Nogent-sur-Marne","addressCountry":"FR"},"areaServed":["Paris","Île-de-France","France","Europe"],"openingHoursSpecification":[{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday"],"opens":"09:00","closes":"18:00"},{"@type":"OpeningHoursSpecification","dayOfWeek":"Friday","opens":"09:00","closes":"17:00"}],"knowsLanguage":["fr","en","es","pt"]},{"@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in FAQ_DATA()]}]}
 return '<script type="application/ld+json">'+json.dumps(data,ensure_ascii=False)+'</script>'

def write(key,body,desc=None,head=''):
 p=OUT/url(key).lstrip('/');p.mkdir(parents=True,exist_ok=True);(p/'index.html').write_text(shell(key,body,desc,head))
if __name__=='__main__':
 for LANG in ['fr','en']:write('home',home(),None,home_jsonld())
 (OUT/'index.html').write_text((OUT/'fr/index.html').read_text())
