import build as b
from build import t,label,url,link,img,video,toggle,eyebrow,actions,cta,cta_strip,steps,faqs,PHONE,PHONE_HREF
from pages import crumb
from motion_pages import particuliers_body,formula_slider
from interactive import formules_quiz,monte_tool,europe_tool,entreprises_tool,stockage_tool,objet_tool,zones_tool,apropos_gallery,checklist
TOOLS={'entreprises':entreprises_tool,'europe':europe_tool,'stockage':stockage_tool,'monte':monte_tool,'piano':objet_tool}
from v1content import V1,PROJECT_OF,v1_blocks,formules_table,zones_steps,conseils_extra,proof_page
SERVICES={
'particuliers':('particuliers','particuliers','Particuliers et successions','Home moves & estate clearances','Déménagement<br>de particuliers','Moving home.<br>A fresh start.','Un appartement, une maison, une succession. CODEM organise votre déménagement selon votre logement, vos accès, vos biens et les prestations choisies.','A flat, a house or an estate clearance. CODEM organises your move around your property, access, belongings and chosen services.'),
'entreprises':('entreprises','entreprises','Transferts professionnels','Business relocation','Votre activité.<br><em>Une nouvelle adresse.</em>','Your business.<br><em>A new address.</em>','Du mobilier aux postes de travail, nous préparons votre transfert en tenant compte de vos locaux, de vos équipements et de votre organisation.','From furniture to workstations, we prepare your relocation around your premises, equipment and business organisation.'),
'europe':('europe','route','Déménagement national & européen','National & European moves','Plus loin.<br><em>Toujours à vos côtés.</em>','Further afield.<br><em>Still by your side.</em>','Une autre ville, une autre région, un autre pays. CODEM étudie votre trajet pour organiser les prestations adaptées à votre destination.','A new city, region or country. CODEM assesses your route to organise services suited to your destination.'),
'stockage':('ancien-33',None,'Garde-meubles','Storage','Entre deux adresses.<br><em>Une place pour vos biens.</em>','Between two homes.<br><em>Space for your belongings.</em>','Un décalage entre deux logements, des travaux ou un besoin d’espace. Étudions ensemble le volume à entreposer et la durée souhaitée.','A gap between homes, renovation work or a need for space. Let’s assess the volume to store and your preferred duration.'),
'monte':('ancien-24',None,'Monte-meubles','Furniture lift','Prendre de la hauteur.<br><em>Avec les moyens adaptés.</em>','Reaching higher.<br><em>With suitable equipment.</em>','Pour certains meubles et certaines configurations, le monte-meubles peut faciliter la manutention. Sa mise en place est toujours étudiée selon les accès.','For some furniture and access arrangements, a furniture lift can simplify handling. Its use is always assessed against site conditions.'),
'piano':('piano','piano','Objets fragiles & spécialisés','Fragile & specialist items','Ce qui a de la valeur.<br><em>Et toute votre confiance.</em>','What you treasure.<br><em>Handled with care.</em>','Pianos, tableaux, miroirs, objets fragiles ou volumineux : leurs particularités demandent une préparation attentive et des moyens adaptés.','Pianos, artwork, mirrors, fragile or bulky items: their specific requirements call for careful preparation and suitable equipment.')}
def photo_section(key):
 photos={
 'particuliers':[(13,'Préparer les cartons','Preparing moving boxes'),(19,'Chargement devant une maison','Loading outside a home')],
 'entreprises':[(16,'Une zone de chargement en ville','An urban loading area'),(18,'Archives à organiser pour le transfert','Records to organise before relocation')],
 'europe':[(12,'Les véhicules de transport CODEM','CODEM transport vehicles'),(20,'Une intervention en région parisienne','A move in Greater Paris')],
 'monte':[(22,'Manutention dans une cour intérieure','Handling in an inner courtyard'),(25,'Un accès par l’extérieur','Access from outside')],
 'piano':[(26,'Manutention d’un objet volumineux','Handling a bulky item'),(29,'Le soin du mobilier de caractère','Care for distinctive furniture')],
 }
 data=photos.get(key,[])
 if not data:return ''
 figures=''.join(f'<figure class="no-margin"><div class="image-wrap">{img("ancien-"+str(i).zfill(2),t(fr,en))}</div><figcaption class="caption">{t(fr,en)}</figcaption></figure>' for i,fr,en in data)
 return f'<section class="section service-photographs"><div class="wrap"><div class="section-heading"><div>{eyebrow("En images","In pictures")}<h2>{t("Des gestes. Des moyens.<br><em>Une attention concrète.</em>","Care in action.<br><em>The right resources.</em>")}</h2></div></div><div class="real-grid">{figures}</div></div></section>'

def service(key):
 im,film,eyfr,eyen,fr,en,descfr,descen=SERVICES[key]
 visual=video(film,True)+toggle() if film else img(im,label(key),eager=True)
 tabs='<nav class="wrap service-tabs" aria-label="'+t('Tous les services','All services')+'">'+''.join(link(k,extra='aria-current="page"' if key==k else '') for k in SERVICES)+'</nav>'
 head=crumb(key)+f'<section class="page-intro"><div class="wrap split"><div>{eyebrow(eyfr,eyen)}<h1>{t(fr,en)}</h1><p class="lead">{t(descfr,descen)}</p><div class="actions"><a class="btn btn-cta" href="{url("devis")}?service={PROJECT_OF[key]}">{t("Demander un devis","Get a quote")}</a>{link("contact",t("Être rappelé","Request a callback"),"btn outline")}</div></div><div><div class="image-wrap">{visual}</div>'+'</div></div></section>'+tabs
 if key=='particuliers':return head+particuliers_body()
 data={
 'entreprises':[
 ('Préparer le transfert, poste par poste.','Plan the move, workstation by workstation.','L’inventaire du mobilier, des équipements et des archives permet de préciser le volume, les protections et l’organisation du transfert. Signalez les équipements qui demandent une manutention spécifique.','An inventory of furniture, equipment and records helps define volume, protection and organisation. Tell us about equipment requiring specialist handling.'),
 ('Organiser les accès et la remise en place.','Plan access and placement.','Étages, ascenseurs, zones de chargement et implantation des postes à l’arrivée sont étudiés en amont. La préparation et l’installation sont définies selon les prestations convenues.','Floors, lifts, loading areas and the destination layout are reviewed in advance. Preparation and installation are defined by the agreed services.'),
 ('Préciser le calendrier.','Agree the schedule.','Indiquez vos contraintes de dates, les équipes concernées et les étapes du transfert. CODEM étudie l’organisation possible avant de confirmer son intervention.','Share your dates, teams involved and relocation stages. CODEM assesses the arrangements before confirming the move.')],
 'europe':[
 ('Un trajet qui se prépare.','A journey planned with care.','Destination, volume, dates et accès au départ comme à l’arrivée : ces éléments permettent d’étudier l’organisation du transport. Les dates de départ et la durée du trajet sont confirmées après cette étude.','Destination, volume, dates and access at both ends help determine transport arrangements. Departure dates and journey times are confirmed after this assessment.'),
 ('La France et des horizons européens.','France and European destinations.','CODEM étudie les déménagements en France et en Europe, notamment vers l’Espagne, le Portugal et l’Italie. Votre destination et les prestations souhaitées sont précisées lors du devis.','CODEM assesses moves within France and across Europe, including Spain, Portugal and Italy. Your destination and services are confirmed in your quote.'),
 ('Les particularités de votre destination.','Your destination’s specific requirements.','Les conditions d’accès et, selon le pays, les documents à prévoir sont à examiner avant le départ. Échangeons sur votre situation pour préparer les informations utiles.','Access conditions and, depending on the country, required documents should be reviewed before departure. Tell us about your plans so we can identify the information needed.')],
 'stockage':[
 ('Le bon volume, pour la bonne durée.','The right space, for the right duration.','Précisez les meubles et cartons à entreposer, la date de dépôt et la durée envisagée. Ces informations permettent à CODEM de vous présenter une proposition adaptée.','Tell us which furniture and boxes need storing, your arrival date and expected duration. CODEM can then prepare a suitable proposal.'),
 ('Préparer les biens avant le dépôt.','Prepare belongings before storage.','Emballage, protection du mobilier et inventaire sont à organiser selon les prestations retenues. Signalez les objets fragiles ou particuliers afin d’étudier leur prise en charge.','Packing, furniture protection and inventory are arranged according to your selected services. Mention fragile or specialist items so their handling can be assessed.'),
 ('Anticiper la restitution.','Plan the return.','Les modalités d’accès, de retrait et de livraison à la nouvelle adresse sont précisées avec CODEM. Le devis doit confirmer les conditions de stockage correspondant à votre besoin.','Access, collection and delivery to your new address are agreed with CODEM. Your quote confirms the storage terms relevant to your needs.')],
 'monte':[
 ('Étudier la configuration.','Assess the location.','L’étage, les dimensions des ouvertures, la façade et l’espace disponible au sol déterminent la faisabilité. Une intervention n’est confirmée qu’après étude.','The floor, opening dimensions, facade and available ground space determine feasibility. An intervention is confirmed only after assessment.'),
 ('Prévoir le stationnement.','Plan parking and positioning.','L’emplacement du véhicule et les éventuelles autorisations d’occupation doivent être anticipés. Indiquez les contraintes connues pour préparer l’intervention.','Vehicle positioning and any required occupancy permissions need advance planning. Tell us about known restrictions so the intervention can be prepared.'),
 ('Adapter la manutention.','Match handling to your furniture.','Dimensions, poids et fragilité des biens sont examinés pour définir les moyens appropriés. Le monte-meubles est une possibilité étudiée, pas une solution systématique.','Dimensions, weight and fragility are assessed to identify suitable equipment. A furniture lift is one option to consider, not a universal solution.')],
 'piano':[
 ('Comprendre l’objet avant de le déplacer.','Understand the item before moving it.','Nature de l’objet, dimensions, poids estimé et particularités de manutention : partagez les informations dont vous disposez. Un piano demande une étude différente d’un tableau ou d’un meuble ancien.','Type, dimensions, estimated weight and handling requirements: share the information you have. A piano needs a different assessment from a painting or an antique cabinet.'),
 ('Choisir les protections adaptées.','Choose suitable protection.','Couvertures, protections d’angles, emballages et maintien sont définis selon l’objet et la prestation. L’objectif est de préparer une manutention attentive, du départ à l’arrivée.','Blankets, corner protection, packing and securing methods are selected for the item and service. The aim is careful handling from collection to delivery.'),
 ('Étudier le chemin complet.','Assess the entire route.','Portes, escaliers, ascenseurs, stationnement et emplacement final sont examinés avant de confirmer les moyens nécessaires. Signalez toute contrainte dès le premier échange.','Doors, stairs, lifts, parking and final placement are assessed before equipment is confirmed. Mention any constraints in your first enquiry.')]
 }[key]
 sections=''.join(f'<article class="reveal"><span class="eyebrow">0{i+1}</span><h3>{t(a,c)}</h3><p>{t(d,e)}</p></article>' for i,(a,c,d,e) in enumerate(data))
 extra=''
 if key=='europe':extra=f'<section class="section dark"><div class="wrap intro-grid"><h2>{t("France.<br>Espagne. Portugal. Italie.<br><em>Et votre destination.</em>","France.<br>Spain. Portugal. Italy.<br><em>And your destination.</em>")}</h2><div><p>{t("Chaque déménagement fait l’objet d’une étude. Parlons de votre projet pour préciser les possibilités et les conditions du trajet.","Every move is assessed individually. Let’s discuss your project to confirm route options and arrangements.")}</p>{link("zones",cls="btn light")}</div></div></section>'
 return head+TOOLS[key]()+v1_blocks(key)+f'<section class="section band-ivory"><div class="wrap"><div class="section-heading"><h2>{t("Le bon soin.<br><em>La bonne préparation.</em>","The right care.<br><em>The right preparation.</em>")}</h2></div><div class="article-grid">{sections}</div></div></section>'+extra+photo_section(key)+f'<section class="section band-glacier"><div class="wrap faq-grid"><div>{eyebrow("Préparons votre projet","Let’s plan your move")}<h2>{t("Vos questions.<br><em>Nos premiers repères.</em>","Your questions.<br><em>A place to start.</em>")}</h2></div><div>{faqs()}</div></div></section>'+cta()

def general(key):
 title={
 'formules':('Votre déménagement.<br><em>À votre mesure.</em>','Your move.<br><em>Your way.</em>'),
 'zones':('D’ici, vers<br><em>votre prochain chez-vous.</em>','From here, to<br><em>your next home.</em>'),
 'apropos':('Une organisation claire.<br><em>Une attention humaine.</em>','Clear organisation.<br><em>A human touch.</em>'),
 'conseils':('Un départ bien préparé.<br><em>Une arrivée plus sereine.</em>','A well-prepared departure.<br><em>A smoother arrival.</em>')}
 head=crumb(key)+f'<section class="page-title"><div class="wrap">{eyebrow(*b.labels[key])}<h1>{t(*title[key])}</h1></div></section>'
 if key=='formules':return head+f'''<section class="section band-ivory" style="padding-top:0"><div class="wrap split"><div><p class="lead">{t('CODEM propose cinq formules, de Self à Grand Confort. Partez de ce que vous souhaitez préparer vous-même et de ce que vous préférez confier à l’équipe.','CODEM offers five packages, from Self to Grand Confort. Start with what you would like to do yourself and what you would rather leave to the team.')}</p><ul class="check-list light-list"><li>{t('Fourniture des cartons et emballages','Supply of boxes and packing materials')}</li><li>{t('Emballage et déballage, selon les objets','Packing and unpacking, depending on the items')}</li><li>{t('Démontage et remontage du mobilier','Furniture dismantling and reassembly')}</li><li>{t('Transport, manutention et remise en place','Transport, handling and placement')}</li></ul><div class="actions"><a class="btn btn-cta" href="{url('devis')}?service=particulier">{t('Choisir ma formule dans le devis','Choose my package in the quote')}</a>{link('contact',t('Être conseillé','Get advice'),'btn outline')}</div></div><div class="image-wrap">{img('ancien-17',t('Cartons et fournitures de déménagement','Moving boxes and packing supplies'))}</div></div></section>{formula_slider()}{formules_quiz()}{cta()}'''
 if key=='zones':return head+zones_tool()+f'''<section class="section" style="padding-top:0"><div class="wrap"><p class="lead">{t('Basée à Nogent-sur-Marne, CODEM dessert Paris et l’Île-de-France et étudie les déménagements en France et en Europe.','Based in Nogent-sur-Marne, CODEM serves Paris and Greater Paris and assesses moves across France and Europe.')}</p><div class="wide-film inset">{video('route')}<div class="film-copy"><h2>{t('Chaque destination<br><em>a son chemin.</em>','Every destination<br><em>has its own journey.</em>')}</h2></div>{toggle()}</div><div class="zone-list inset"><article><h3>Paris & Île-de-France</h3><p>{t('Départ ou arrivée en région parisienne : logements, bureaux, étages et accès sont étudiés pour préparer le déménagement.','Collection or delivery in Greater Paris: homes, offices, floors and access are assessed before the move.')}</p></article><article><h3>France</h3><p>{t('Un changement de ville ou de région, avec une organisation adaptée au volume, à la distance et à votre calendrier.','A move to another town or region, planned around volume, distance and your schedule.')}</p></article><article><h3>Europe</h3><p>{t('Espagne, Portugal, Italie et autres destinations à étudier avec CODEM. Les conditions sont précisées avant confirmation.','Spain, Portugal, Italy and other destinations to discuss with CODEM. Arrangements are confirmed in advance.')}</p></article></div></div></section>{zones_steps()}{cta()}'''
 if key=='apropos':return head+f'''<section class="section" style="padding-top:0"><div class="wrap split"><div><p class="lead">{t('Un déménagement rassemble de nombreux gestes. Notre rôle est de les organiser autour de votre projet.','A move involves many individual tasks. Our role is to organise them around your needs.')}</p><p>{t('CODEM accompagne les particuliers et les entreprises au départ ou à destination de Paris, de l’Île-de-France, de la France et de l’Europe. Préparation, protection, manutention, transport et installation sont coordonnés selon les prestations convenues.','CODEM supports households and businesses moving to or from Paris, Greater Paris, France and Europe. Preparation, protection, handling, transport and installation are coordinated according to the agreed services.')}</p><p>{t('Notre point de départ : comprendre votre situation, les biens à déplacer et les contraintes des lieux. Puis préciser ensemble les moyens et les prestations adaptés.','We start by understanding your situation, the belongings to move and site constraints. Then we agree suitable resources and services together.')}</p>{link('contact',t('Rencontrons-nous','Let’s talk'),'btn')}</div><div><div class="image-wrap">{img('ancien-01',t('Façade de l’agence CODEM','CODEM office frontage'))}</div></div></div></section><section class="section band-glacier"><div class="wrap intro-grid"><h2>{t('À Nogent-sur-Marne.<br><em>À vos côtés, plus loin.</em>','In Nogent-sur-Marne.<br><em>By your side, further afield.</em>')}</h2><div><p>39 boulevard de Strasbourg<br>94130 Nogent-sur-Marne</p><p><a href="tel:+33171361838">01 71 36 18 38</a><br><a href="tel:+33667570912">06 67 57 09 12</a></p><p>{t('Lundi – jeudi : 9 h – 12 h et 13 h – 18 h · vendredi jusqu’à 17 h','Monday – Thursday: 9 am – 12 pm and 1 pm – 6 pm · Friday until 5 pm')}<br>{t('Langues : français, anglais, espagnol, portugais','Languages: French, English, Spanish, Portuguese')}</p></div></div></section>{apropos_gallery()}{cta()}'''
 articles=[('Avant le devis','Before your quote','Faites le tour de chaque pièce et listez le mobilier principal. Notez les objets fragiles, les éléments à démonter et ce qui devra être stocké. Une surface approximative est utile si vous ne connaissez pas le volume.','Walk through every room and list the main furniture. Note fragile items, pieces to dismantle and anything requiring storage. An approximate floor area helps if you do not know the volume.'),('Repérer les accès','Check access','Relevez les étages, la présence et les dimensions de l’ascenseur, les escaliers étroits et les possibilités de stationnement aux deux adresses. Signalez les contraintes avant de confirmer le devis.','Record floors, lift availability and dimensions, narrow stairs and parking options at both addresses. Mention restrictions before confirming your quote.'),('Préparer les cartons','Prepare your boxes','Regroupez les objets par pièce, identifiez le contenu et signalez les cartons fragiles. Gardez les charges raisonnables. Convenez avec CODEM des emballages et de la préparation à votre charge.','Pack by room, label contents and mark fragile boxes. Keep weights manageable. Agree with CODEM which materials and preparation you will handle.'),('Les objets particuliers','Specialist items','Signalez les pianos, tableaux, miroirs et meubles volumineux. Préparez leurs dimensions et toute information utile sur leur fragilité. La manutention doit être étudiée avant le jour du déménagement.','Mention pianos, artwork, mirrors and bulky furniture. Prepare dimensions and information about fragility. Handling needs assessment before moving day.'),('Le jour du départ','On moving day','Gardez accessibles vos documents, médicaments, clés et effets essentiels. Vérifiez avec l’équipe les prestations convenues et les objets qui demandent une attention particulière.','Keep documents, medication, keys and essentials accessible. Review the agreed services and items needing special attention with the team.'),('Préparer l’arrivée','Prepare for arrival','Anticipez l’emplacement des meubles et l’accès aux pièces. Les indications sur les cartons facilitent la remise en place. Faites le point sur la prestation avec l’équipe avant son départ.','Plan furniture placement and room access. Clear box labels help with placement. Review the service with the team before they leave.')]
 articles+=conseils_extra()
 return head+checklist()+'<section class="band-ivory"><div class="wrap"><div class="image-wrap wide-visual">'+img('famille-installee',t('Une famille installée dans son nouveau logement','A family settled into their new home'))+'</div></div></section>'+'<section class="section band-ivory" style="padding-top:0"><div class="wrap article-grid">'+''.join(f'<article><span class="eyebrow">{str(i+1).zfill(2)}</span><h2>{t(a,c)}</h2><p>{t(d,e)}</p></article>' for i,(a,c,d,e) in enumerate(articles))+'</div></section>'+cta_strip('Votre liste est prête ? Passons au devis.','Got your list ready? Let’s do the quote.')+cta()

def legal(key):
 contents={
 'legal':[("Éditeur du site","Site publisher","CODEM — 39 boulevard de Strasbourg, 94130 Nogent-sur-Marne. Téléphone : 01 71 36 18 38 / 06 67 57 09 12. Ces coordonnées sont issues des documents fournis et restent à confirmer avant ouverture au public.","CODEM — 39 boulevard de Strasbourg, 94130 Nogent-sur-Marne, France. Phone: +33 1 71 36 18 38 / +33 6 67 57 09 12. These details come from the supplied documents and must be confirmed before public release."),("Informations à compléter avant publication publique","Information required before public release","La dénomination sociale exacte, la forme juridique, le capital social, le numéro SIREN / RCS, le numéro de TVA le cas échéant, l’adresse e-mail, le directeur de publication et les coordonnées légales de l’hébergeur doivent être fournis et validés par CODEM.","CODEM must supply and validate its full legal name, legal form, share capital, company registration number, VAT number where applicable, email address, publication director and hosting provider’s legal details.")],
 'privacy':[("Les demandes envoyées depuis le site","Enquiries sent from this site","Lorsque vous envoyez une demande de devis, de rappel, de visite ou un message, les informations saisies (coordonnées, détails du déménagement, préférences de contact) sont transmises à CODEM et enregistrées dans une base de données hébergée par le prestataire Supabase. Elles servent uniquement à répondre à votre demande et à préparer votre déménagement. Les photos sélectionnées dans le devis ne sont pas transmises : seul leur nom de fichier est indiqué. Aucun service de mesure d’audience ni traceur publicitaire n’est activé.","When you send a quote, callback, survey-visit request or a message, the details you enter (contact details, move details, contact preferences) are sent to CODEM and stored in a database hosted by the provider Supabase. They are used only to answer your request and prepare your move. Photos selected in the quote form are not uploaded: only their file names are included. No audience analytics or advertising trackers are enabled."),("Vos droits","Your rights","Vous pouvez demander l’accès, la rectification ou la suppression de vos informations en contactant CODEM au 01 71 36 18 38 ou par courrier au 39 boulevard de Strasbourg, 94130 Nogent-sur-Marne.","You can ask to access, correct or delete your details by contacting CODEM on +33 1 71 36 18 38 or by post at 39 boulevard de Strasbourg, 94130 Nogent-sur-Marne."),("Vos préférences","Your preferences","Le choix effectué dans la fenêtre de confidentialité est enregistré localement dans votre navigateur. Vous pouvez le modifier via le lien « Préférences de confidentialité » en pied de page ou l’effacer dans les réglages du navigateur.","Your privacy-dialog choice is saved locally in your browser. You can change it using the footer privacy link or clear it in your browser settings.")],
 'cookies':[("Aucun traceur non essentiel activé","No non-essential trackers enabled","Cette version ne dépose aucun cookie publicitaire ni cookie de mesure d’audience. Les vidéos sont servies directement par le site, sans lecteur vidéo tiers intégré.","This version sets no advertising or audience analytics cookies. Videos are served directly by the site, without an embedded third-party player."),("Votre choix reste accessible","Your choice remains accessible","Les boutons « Tout accepter » et « Tout refuser » sont accessibles dans les préférences de confidentialité. Ils ne déclenchent aucun outil de suivi dans cette version. Le choix est conservé localement sous la clé codem-privacy.","Accept all and Reject all are available in privacy preferences. Neither enables tracking in this version. Your choice is stored locally under codem-privacy."),("Si de nouveaux outils sont ajoutés","If new tools are added","Cette information et le mécanisme de choix devront être adaptés avant l’activation d’outils non essentiels.","This notice and the preference controls must be updated before non-essential tools are enabled.")],
 'access':[("Une navigation pensée pour tous","Designed for inclusive navigation","Le site propose une navigation au clavier, des intitulés de champs, des contrastes étudiés et des contrôles pour mettre les vidéos en pause. Les animations respectent le réglage de réduction des mouvements du navigateur.","The site provides keyboard navigation, field labels, considered contrast and video pause controls. Animations respect the browser’s reduced-motion preference."),("État de l’évaluation","Evaluation status","Aucun audit formel de conformité RGAA n’a été réalisé. Cette page ne constitue donc pas une déclaration de conformité. Les éventuelles difficultés peuvent être signalées par téléphone à CODEM.","No formal RGAA accessibility audit has been carried out. This page is not a declaration of compliance. Please report any difficulties to CODEM by phone."),("Nous contacter","Contact us","Pour obtenir une information ou de l’aide dans votre démarche : 01 71 36 18 38 ou 06 67 57 09 12.","For information or help with your enquiry, call +33 1 71 36 18 38 or +33 6 67 57 09 12.")]
 }
 return crumb(key)+f'<section class="section" style="padding-top:25px"><div class="wrap content-narrow"><h1>{label(key)}</h1>'+''.join(f'<h2>{t(a,c)}</h2><p>{t(d,e)}</p>' for a,c,d,e in contents[key])+('</div></section>')

if __name__=='__main__':
 for lang in ['fr','en']:
  b.LANG=lang
  for k in SERVICES:b.write(k,service(k),t(SERVICES[k][6],SERVICES[k][7]))
  for k in ['formules','zones','apropos','conseils']:b.write(k,general(k),t('Découvrez '+label(k).lower()+' avec CODEM : des informations utiles pour préparer votre déménagement.','Explore '+label(k).lower()+' with CODEM: useful information for planning your move.'))
  for k in ['avis','realisations']:b.write(k,proof_page(k),t('CODEM Déménagements : '+label(k).lower()+', publiés avec leur source et l’accord des clients.','CODEM Moving: '+label(k).lower()+', published with their source and client consent.'))
  for k in ['legal','privacy','cookies','access']:b.write(k,legal(k),t('Informations CODEM : '+label(k)+'.','CODEM information: '+label(k)+'.'))
