"""Outils interactifs des pages intérieures (lots 2 à 4). Chaque outil oriente le visiteur
et ouvre le devis pré-rempli ; aucun ne calcule de prix."""
import build as b
from build import t,url,link,img,eyebrow

def q(name,fr,en,opts):
 o=''.join(f'<label class="pick"><input type="radio" name="{name}" value="{v}"><span>{t(a,c)}</span></label>' for v,a,c in opts)
 return f'<fieldset class="tool-q"><legend>{t(fr,en)}</legend><div class="picks">{o}</div></fieldset>'

def tool_shell(cls,eyfr,eyen,hfr,hen,pfr,pen,body,result,band='band-sand'):
 return f'''<section class="section {band} tool {cls}" data-tool="{cls}"><div class="wrap tool-grid"><div class="tool-intro">{eyebrow(eyfr,eyen)}<h2>{t(hfr,hen)}</h2><p class="subtle">{t(pfr,pen)}</p></div><div class="tool-card"><form class="tool-form" novalidate>{body}</form><div class="tool-result" aria-live="polite" hidden>{result}</div></div></div></section>'''

DEVIS=lambda:url('devis')

# --- Formules : quiz -------------------------------------------------------
def formules_quiz():
 body=q('emballage','Qui emballe vos affaires ?','Who packs your belongings?',[('moi','Moi, tout','Me, everything'),('fragile','CODEM, le fragile','CODEM, fragile items'),('tout','CODEM, tout','CODEM, everything')])+q('meubles','Démontage et remontage des meubles ?','Dismantling and reassembly?',[('moi','Je m’en occupe','I’ll do it'),('codem','CODEM s’en occupe','CODEM does it')])+q('arrivee','À l’arrivée, le déballage ?','Unpacking on arrival?',[('moi','Je déballe','I unpack'),('fragile','CODEM, le fragile','CODEM, fragile items'),('tout','CODEM, tout','CODEM, everything')])
 result=f'<span class="eyebrow">{t("Formule conseillée","Recommended package")}</span><p class="tool-big" data-out="name"></p><p data-out="desc"></p><a class="btn btn-cta btn-lg" data-out="cta" href="{DEVIS()}">{t("Demander un devis","Get a quote")}</a><button type="button" class="text-link tool-reset">{t("Refaire le quiz","Retake the quiz")}</button>'
 return tool_shell('quiz-formule','Quelle formule pour vous ?','Which package suits you?','Trois questions.<br><em>Une formule conseillée.</em>','Three questions.<br><em>One recommendation.</em>','Répondez en quelques secondes : nous vous orientons vers la formule qui correspond à ce que vous voulez déléguer.','Answer in seconds: we point you to the package that matches what you want to hand over.',body,result,'band-glacier')

# --- Monte-meubles : test de faisabilité + jauge d'étages -------------------
def monte_tool():
 body=q('etage','À quel étage ?','Which floor?',[('1-2','1er – 2e','1st – 2nd'),('3-5','3e – 5e','3rd – 5th'),('6+','6e et plus','6th or higher')])+q('fenetre','Une fenêtre ou un balcon accessible côté rue ?','A street-side window or balcony?',[('oui','Oui','Yes'),('non','Non','No'),('nsp','Je ne sais pas','Not sure')])+q('stationnement','Peut-on stationner devant l’immeuble ?','Can a vehicle park in front?',[('oui','Oui','Yes'),('reserver','À réserver','Needs booking'),('non','Difficile','Difficult')])+q('objets','Quels objets ?','Which items?',[('canape','Canapé, armoire','Sofa, wardrobe'),('piano','Piano','Piano'),('tout','Tout le déménagement','The whole move')])
 result=f'<span class="eyebrow">{t("Premier avis","First opinion")}</span><p class="tool-big" data-out="name"></p><p data-out="desc"></p><a class="btn btn-cta btn-lg" data-out="cta" href="{DEVIS()}?service=monte-meubles">{t("Réserver une étude","Book an assessment")}</a><button type="button" class="text-link tool-reset">{t("Recommencer","Start again")}</button>'
 floors=''.join(f'<li data-floor="{n}"><span>{n}{t("e" if n>1 else "er","")}</span></li>' for n in range(6,0,-1))
 gauge=f'''<section class="section band-navy lift-band"><div class="wrap lift-grid"><div class="lift-photo image-wrap">{img('monte-meubles',t('Monte-meubles CODEM en intervention','CODEM furniture lift at work'))}<ol class="lift-gauge" aria-hidden="true">{floors}<li class="lift-ground"><span>RDC</span></li></ol><span class="lift-cab" aria-hidden="true"></span></div><div>{eyebrow('Par la fenêtre','Through the window')}<h2>{t('Jusqu’à l’étage,<br><em>sans passer par l’escalier.</em>','Up to the floor,<br><em>without the stairs.</em>')}</h2><p>{t('Le monte-meubles hisse canapés, armoires et pianos jusqu’à la fenêtre, manœuvré par un technicien CODEM. L’escalier et les parties communes restent protégés.','The lift raises sofas, wardrobes and pianos to the window, operated by a CODEM technician. Stairs and shared areas stay protected.')}</p><p class="lift-floor-read"><strong data-lift-floor>RDC</strong> · {t('faites défiler','scroll')}</p></div></div></section>'''
 return gauge+tool_shell('test-monte','Test de faisabilité','Feasibility check','Le monte-meubles,<br><em>possible chez vous ?</em>','A furniture lift,<br><em>possible at your place?</em>','Quatre questions pour un premier avis. Le conseiller confirme ensuite l’équipement, le créneau et les autorisations.','Four questions for a first opinion. The adviser then confirms equipment, timing and permits.',body,result)

# --- France & Europe : destinations ---------------------------------------
DEST=[('ES','Espagne','Spain','Madrid · Barcelone · Valence','Madrid · Barcelona · Valencia'),('PT','Portugal','Portugal','Lisbonne · Porto · Algarve','Lisbon · Porto · Algarve'),('IT','Italie','Italy','Rome · Milan · Turin','Rome · Milan · Turin'),('BE','Belgique','Belgium','Bruxelles · Liège · Anvers','Brussels · Liège · Antwerp'),('CH','Suisse','Switzerland','Genève · Lausanne · Zurich','Geneva · Lausanne · Zurich'),('FR','France','France','Toutes les régions','All regions')]
def europe_tool():
 chips=''.join(f'<button type="button" class="dest" data-country="{t(a,c)}" data-cities="{t(d,e)}"><span class="dest-code">{k}</span>{t(a,c)}</button>' for k,a,c,d,e in DEST)
 return f'''<section class="section band-glacier tool dest-tool"><div class="wrap"><div class="section-heading"><div>{eyebrow('Où partez-vous ?','Where are you going?')}<h2>{t('Choisissez votre destination.<br><em>On trace la route.</em>','Pick your destination.<br><em>We plan the route.</em>')}</h2></div></div><div class="dest-grid"><div class="dest-chips">{chips}</div><div class="dest-card"><div class="dest-route" aria-hidden="true"><span class="dr-a">A</span><span class="dr-line"><span class="dr-fill"></span><span class="dr-truck"></span></span><span class="dr-b">B</span></div><div class="dest-names"><span>Nogent-sur-Marne</span><strong data-dest-name>{t('Votre destination','Your destination')}</strong></div><p class="subtle" data-dest-cities>{t('Sélectionnez un pays ou saisissez une ville.','Select a country or type a city.')}</p><form class="dest-form" action="{DEVIS()}" method="get"><input type="hidden" name="service" value="particulier"><input type="hidden" name="pays" data-dest-country><label class="sr-only" for="dest-city">{t('Ville d’arrivée','Destination city')}</label><input id="dest-city" name="arrivee" placeholder="{t('Ville d’arrivée (ex. Lisbonne)','Destination city (e.g. Lisbon)')}" autocomplete="off"><label class="check"><input type="checkbox" name="groupage" value="oui"><span>{t('Étudier une option de groupage','Consider a shared load')}</span></label><button class="btn btn-cta btn-block" type="submit">{t('Préparer mon devis','Prepare my quote')}</button></form></div></div></div></section>'''

# --- Entreprises : mini-formulaire + calendrier -----------------------------
TIMELINE=[('J-30','D-30','Inventaire','Inventory','Recensement des postes, du mobilier, des archives et des équipements.','Workstations, furniture, records and equipment are listed.'),('J-15','D-15','Planning','Schedule','Calendrier validé, marquage et étiquetage préparés pour chaque service.','Schedule agreed, marking and labelling prepared for each team.'),('J-7','D-7','Mise en cartons','Packing','Dossiers et archives mis en cartons, documents confidentiels isolés.','Files and records boxed, confidential documents kept apart.'),('J-1','D-1','Démontage','Dismantling','Démontage et protection du mobilier, souvent en fin de journée.','Furniture dismantled and protected, often after hours.'),('Jour J','D-Day','Transfert','Relocation','Chargement, transport et livraison sur le nouveau site.','Loading, transport and delivery to the new site.'),('J+1','D+1','Remise en place','Set-up','Remontage, mise en place des postes : vos équipes reprennent le travail.','Reassembly and set-up: your teams get back to work.')]
def entreprises_tool():
 cards=''.join(f'<article class="tl-card"><span class="tl-day">{t(a,c)}</span><h3>{t(d,e)}</h3><p>{t(f,g)}</p></article>' for a,c,d,e,f,g in TIMELINE)
 form=f'''<section class="section band-sand tool b2b-tool"><div class="wrap tool-grid"><div class="tool-intro">{eyebrow('Transfert professionnel','Business relocation')}<h2>{t('Votre transfert<br><em>en 30 secondes.</em>','Your relocation<br><em>in 30 seconds.</em>')}</h2><p class="subtle">{t('Indiquez la taille de vos locaux : un conseiller dédié vous rappelle pour organiser une visite technique.','Tell us the size of your premises: a dedicated adviser calls back to arrange a site visit.')}</p></div><div class="tool-card"><form class="b2b-form" action="{DEVIS()}" method="get"><input type="hidden" name="service" value="entreprise"><input type="hidden" name="logement" value="bureaux"><div class="fields"><div class="field"><label for="b2b-postes">{t('Nombre de postes','Workstations')}</label><input id="b2b-postes" type="number" min="1" data-b2b="postes"></div><div class="field"><label for="b2b-surface">{t('Surface (m²)','Area (m²)')}</label><input id="b2b-surface" type="number" min="1" name="surface"></div><div class="field"><label for="b2b-depart">{t('Ville actuelle','Current city')}</label><input id="b2b-depart" name="depart"></div><div class="field"><label for="b2b-date">{t('Date souhaitée','Preferred date')}</label><input id="b2b-date" type="date" name="date" data-min-today></div></div><input type="hidden" name="objets" data-b2b-objets><input type="hidden" name="contraintes" data-b2b-contraintes><label class="check"><input type="checkbox" data-b2b="horaires"><span>{t('Intervention hors horaires (soir, week-end)','Out-of-hours work (evening, weekend)')}</span></label><button class="btn btn-cta btn-block" type="submit">{t('Démarrer ma demande','Start my request')}</button></form></div></div></section>'''
 tl=f'''<section class="hscroll band-navy tl-band"><div class="hs-sticky"><div class="wrap hs-head">{eyebrow('Un calendrier type','A typical schedule')}<h2>{t('De J-30 à J+1,<br><em>votre activité continue.</em>','From D-30 to D+1,<br><em>business carries on.</em>')}</h2></div><div class="hs-track">{cards}<div class="hs-card hs-end"><p>{t('Chaque calendrier est ajusté à vos contraintes.','Every schedule is adjusted to your constraints.')}</p><a class="btn btn-cta" href="{DEVIS()}?service=entreprise">{t('Planifier une visite','Plan a visit')}</a></div></div><p class="wrap tl-note">{t('Calendrier indicatif, ajusté à votre projet.','Indicative schedule, adjusted to your project.')}</p></div></section>'''
 return form+tl

# --- Garde-meubles : volume + durée -----------------------------------------
def stockage_tool():
 return f'''<section class="section band-sand tool box-tool"><div class="wrap tool-grid"><div class="tool-intro">{eyebrow('Votre espace','Your space')}<h2>{t('Le bon volume,<br><em>pour la bonne durée.</em>','The right volume,<br><em>for the right time.</em>')}</h2><p class="subtle">{t('Estimez ce que vous voulez entreposer. CODEM confirme le volume avec vous et vous propose une solution adaptée.','Estimate what you want to store. CODEM confirms the volume with you and suggests a suitable solution.')}</p></div><div class="tool-card box-card"><div class="box-gauge" aria-hidden="true"><div class="box-fill"></div><span class="box-m3" data-box-m3>10 m³</span></div><form class="box-form" action="{DEVIS()}" method="get"><input type="hidden" name="service" value="stockage"><input type="hidden" name="prestation" value="garde-meubles"><input type="hidden" name="volume" data-box-volume value="10"><input type="hidden" name="annexes" data-box-annexes><label for="box-range" class="tool-label">{t('Volume à entreposer','Volume to store')}</label><input id="box-range" class="tool-range" type="range" min="2" max="60" step="1" value="10"><p class="box-hint" data-box-hint></p><fieldset class="tool-q"><legend>{t('Pour combien de temps ?','For how long?')}</legend><div class="picks">'''+''.join(f'<label class="pick"><input type="radio" name="duree" value="{t(a,c)}"{" checked" if i==1 else ""}><span>{t(a,c)}</span></label>' for i,(a,c) in enumerate([('Moins d’1 mois','Under 1 month'),('1 à 3 mois','1–3 months'),('3 à 12 mois','3–12 months'),('Plus d’1 an','Over 1 year')]))+f'''</div></fieldset><button class="btn btn-cta btn-block" type="submit">{t('Demander une solution de stockage','Request a storage solution')}</button></form></div></div></section>'''

# --- Objets spécialisés : fiche objet ---------------------------------------
def objet_tool():
 types=[('Piano droit','Upright piano'),('Piano à queue','Grand piano'),('Œuvre d’art, tableau','Artwork, painting'),('Meuble ancien','Antique furniture'),('Objet lourd ou volumineux','Heavy or bulky item'),('Autre objet fragile','Other fragile item')]
 picks=''.join(f'<label class="pick"><input type="radio" name="type" value="{t(a,c)}"><span>{t(a,c)}</span></label>' for a,c in types)
 return f'''<section class="section band-sand tool objet-tool"><div class="wrap tool-grid"><div class="tool-intro">{eyebrow('Fiche objet','Item sheet')}<h2>{t('Décrivez l’objet.<br><em>Nous préparons les protections.</em>','Describe the item.<br><em>We prepare the protection.</em>')}</h2><p class="subtle">{t('Ces informations sont transmises au conseiller avec votre demande, pour choisir l’emballage, la manutention et, si besoin, le monte-meubles.','This information goes to the adviser with your request, to choose packing, handling and, if needed, a furniture lift.')}</p></div><div class="tool-card"><form class="objet-form" action="{DEVIS()}" method="get"><input type="hidden" name="service" value="objet-specialise"><input type="hidden" name="prestation" value="fragiles"><input type="hidden" name="objets" data-objet-out><fieldset class="tool-q"><legend>{t('Quel objet ?','Which item?')}</legend><div class="picks">{picks}</div></fieldset><div class="fields"><div class="field"><label for="obj-dim">{t('Dimensions approximatives','Approximate size')}</label><input id="obj-dim" data-objet="dim" placeholder="{t('ex. 150 × 60 × 130 cm','e.g. 150 × 60 × 130 cm')}"></div><div class="field"><label for="obj-etage">{t('Étage au départ','Floor at collection')}</label><input id="obj-etage" name="etage" placeholder="{t('ex. 3e sans ascenseur','e.g. 3rd, no lift')}"></div></div><button class="btn btn-cta btn-block" type="submit">{t('Demander un devis pour cet objet','Get a quote for this item')}</button></form></div></div></section>'''

# --- Zones : recherche de commune --------------------------------------------
def zones_tool():
 return f'''<section class="section band-glacier tool zone-tool"><div class="wrap tool-grid"><div class="tool-intro">{eyebrow('Votre commune','Your town')}<h2>{t('CODEM intervient-il<br><em>chez vous ?</em>','Does CODEM cover<br><em>your area?</em>')}</h2><p class="subtle">{t('Saisissez votre code postal ou votre ville de départ.','Enter your postcode or departure town.')}</p></div><div class="tool-card"><form class="zone-form" action="{DEVIS()}" method="get"><label class="sr-only" for="zone-q">{t('Code postal ou ville','Postcode or town')}</label><div class="zone-input"><input id="zone-q" name="depart" placeholder="{t('ex. 94300 Vincennes','e.g. 94300 Vincennes')}" autocomplete="postal-code"><button class="btn btn-cta" type="submit">{t('Vérifier','Check')}</button></div></form><div class="zone-answer" aria-live="polite" hidden><div class="dest-route" aria-hidden="true"><span class="dr-a">A</span><span class="dr-line"><span class="dr-fill"></span><span class="dr-truck"></span></span><span class="dr-b">B</span></div><p class="tool-big" data-zone-title></p><p data-zone-text></p><a class="btn btn-cta btn-lg" data-zone-cta href="{DEVIS()}">{t('Continuer vers le devis','Continue to the quote')}</a></div></div></div></section>'''

# --- À propos : la flotte en galerie ----------------------------------------
def apropos_gallery():
 shots=[('ancien-02','Les véhicules CODEM','CODEM vehicles'),('ancien-12','Poids lourd et utilitaire','Truck and van'),('ancien-21','Monte-meubles en intervention','Furniture lift at work'),('ancien-20','À Nogent-sur-Marne','In Nogent-sur-Marne'),('ancien-19','Chargement chez un particulier','Loading at a home'),('ancien-26','Manutention d’un objet d’exception','Handling an exceptional item')]
 cards=''.join(f'<figure class="hs-card">{img(i,t(a,c))}<figcaption><span>0{k+1}</span>{t(a,c)}</figcaption></figure>' for k,(i,a,c) in enumerate(shots))
 return f'''<section class="hscroll band-navy"><div class="hs-sticky"><div class="wrap hs-head">{eyebrow('La flotte CODEM','The CODEM fleet')}<h2>{t('Des moyens réels,<br><em>sur le terrain.</em>','Real resources,<br><em>out in the field.</em>')}</h2></div><div class="hs-track">{cards}<div class="hs-card hs-end"><p>{t('Rencontrez un conseiller CODEM.','Meet a CODEM adviser.')}</p>{link('contact',t('Prendre rendez-vous','Book a meeting'),'btn btn-cta')}</div></div></div></section>'''

# --- Conseils : checklist interactive ----------------------------------------
CHECK=[('J-60','D-60',[('Demander plusieurs devis et une visite technique','Request quotes and a site visit'),('Fixer la date et la formule','Set the date and package'),('Prévenir votre propriétaire ou préparer la vente','Notify your landlord or prepare the sale')]),
 ('J-30','D-30',[('Trier, donner, vendre ce qui ne part pas','Sort, give away or sell what stays'),('Demander l’autorisation de stationnement en mairie','Request a parking permit from the town hall'),('Commander cartons et protections','Order boxes and protection')]),
 ('J-15','D-15',[('Transférer énergie, internet et assurance habitation','Transfer energy, internet and home insurance'),('Faire suivre votre courrier','Set up mail forwarding'),('Commencer les cartons des pièces peu utilisées','Start packing rarely used rooms')]),
 ('J-7','D-7',[('Confirmer horaires et accès avec CODEM','Confirm timing and access with CODEM'),('Vider et dégivrer le réfrigérateur','Empty and defrost the fridge'),('Mettre de côté documents, clés et médicaments','Set aside documents, keys and medication')]),
 ('Jour J','D-Day',[('Faire le tour des pièces avec l’équipe','Walk through each room with the team'),('Relever les compteurs','Read the meters'),('Vérifier que rien n’est oublié','Check nothing is left behind')]),
 ('J+7','D+7',[('Déclarer votre nouvelle adresse aux organismes','Update your address with organisations'),('Défaire les derniers cartons','Unpack the last boxes'),('Donner votre avis à CODEM','Review your move with CODEM')])]
def checklist():
 cols=''
 n=0
 for a,c,items in CHECK:
  lis=''
  for x,y in items:
   lis+=f'<li><label><input type="checkbox" data-ck="{n}"><span>{t(x,y)}</span></label></li>';n+=1
  cols+=f'<article class="ck-col"><span class="tl-day">{t(a,c)}</span><ul>{lis}</ul></article>'
 return f'''<section class="section band-glacier tool checklist"><div class="wrap"><div class="section-heading"><div>{eyebrow('Votre checklist','Your checklist')}<h2>{t('De J-60 à J+7,<br><em>rien n’est oublié.</em>','From D-60 to D+7,<br><em>nothing is forgotten.</em>')}</h2></div><div class="ck-progress"><div class="ck-bar"><span></span></div><p><strong data-ck-count>0</strong> / {n} {t('tâches faites','tasks done')}</p><button type="button" class="btn outline" data-ck-print>{t('Imprimer ma checklist','Print my checklist')}</button></div></div><div class="ck-grid">{cols}</div><p class="fine-print">{t('Vos coches restent enregistrées sur cet appareil.','Your ticks are saved on this device.')}</p></div></section>'''
