"""Pages intérieures « en mouvement » (lot 2 : prototype Particuliers)."""
import build as b
from build import t,url,link,img,eyebrow,cta,faqs
from v1content import GRID,FORMULES

ACT_PHOTOS=[('ancien-01','L’agence CODEM à Nogent-sur-Marne','The CODEM office in Nogent-sur-Marne'),('ancien-10','Mobilier protégé par CODEM','Furniture protected by CODEM'),('ancien-03','Chargement d’un camion CODEM','Loading a CODEM truck'),('ancien-19','Livraison devant une maison','Delivery outside a house')]
def act_photos():
 return '<div class="act-photos">'+''.join(f'<figure class="act-photo" data-photo="{i+1}">{img(n,t(a,c),eager=i==0)}<figcaption>{t(a,c)}</figcaption></figure>' for i,(n,a,c) in enumerate(ACT_PHOTOS))+'</div>'

ACTS=[('Acte 1','Act 1','Vous nous racontez votre projet.','You tell us about your move.','Départ, arrivée, période, type de logement : quelques minutes suffisent. Un conseiller étudie le volume et les accès, et organise une visite lorsque c’est utile.','From, to, dates, type of home: a few minutes are enough. An adviser reviews volume and access, and arranges a visit when useful.',['Devis gratuit, sans engagement','Visite à domicile ou à distance'],['Free, no-obligation quote','Home or video survey']),
 ('Acte 2','Act 2','Nous protégeons ce qui compte.','We protect what matters.','Cartons, papier bulle, housses pour matelas et sommiers, protections pour télévisions, miroirs et tableaux, penderies pour les vêtements sur cintres.','Boxes, bubble wrap, mattress covers, protection for TVs, mirrors and artwork, wardrobe boxes for hanging clothes.',['Emballage du fragile selon la formule','Fourniture des emballages'],['Fragile packing depending on package','Packing materials supplied']),
 ('Acte 3','Act 3','Nous chargeons, nous roulons.','We load, we drive.','Démontage du mobilier, manutention et transport en véhicules capitonnés, adaptés à votre volume. Monte-meubles prévu si l’escalier ne suffit pas.','Furniture dismantling, handling and transport in padded vehicles matched to your volume. A furniture lift is arranged if the stairs are not enough.',['Véhicules capitonnés','Monte-meubles si nécessaire'],['Padded vehicles','Furniture lift if needed']),
 ('Acte 4','Act 4','Vous êtes chez vous.','You are home.','Remontage et mise en place du mobilier, déballage selon votre formule. L’équipe fait le point avec vous avant de partir.','Furniture reassembled and placed, unpacking depending on your package. The team checks everything with you before leaving.',['Remontage et mise en place','Déballage selon la formule'],['Reassembly and placement','Unpacking depending on package'])]

def acts():
 steps=''
 for i,(a,a2,h,h2,p,p2,l,l2) in enumerate(ACTS):
  items=''.join(f'<li>{t(x,y)}</li>' for x,y in zip(l,l2))
  steps+=f'<article class="act" data-act="{i+1}"><span class="act-num">{t(a,a2)}</span><h3>{t(h,h2)}</h3><p>{t(p,p2)}</p><ul class="act-list">{items}</ul></article>'
 dots=''.join(f'<span class="act-dot" data-dot="{i+1}"></span>' for i in range(4))
 return f'''<section class="acts band-ivory" aria-labelledby="acts-title"><div class="wrap"><div class="acts-head">{eyebrow('Comment ça se passe','How it works')}<h2 id="acts-title">{t('Votre déménagement<br><em>en quatre actes.</em>','Your move<br><em>in four acts.</em>')}</h2></div><div class="acts-grid"><div class="acts-stage"><div class="acts-sticky" data-act-stage="1">{act_photos()}<div class="act-progress">{dots}</div></div></div><div class="acts-text">{steps}<div class="act-cta"><a class="btn btn-cta btn-lg" href="{url('devis')}?service=particulier">{t('Commencer mon devis','Start my quote')}</a></div></div></div></div></section>'''

DESC=[('Vous préparez vos cartons. CODEM protège, charge, transporte.','You pack your boxes. CODEM protects, loads and transports.'),('CODEM ajoute le démontage, le remontage et la mise en place du mobilier.','CODEM adds furniture dismantling, reassembly and placement.'),('CODEM emballe aussi le fragile et fournit les emballages.','CODEM also packs fragile items and supplies packing materials.'),('CODEM emballe tout. Vous ne déballez que le non-fragile.','CODEM packs everything. You only unpack non-fragile items.'),('CODEM s’occupe de tout, jusqu’au dernier carton déballé.','CODEM handles everything, down to the last box unpacked.')]
SLUGS=['self','self-plus','confort','confort-plus','grand-confort']
def formula_slider():
 rows=''.join(f'<li class="task" data-codes="{code}"><span class="task-name">{t(a,c)}</span><span class="who" aria-live="off"><span class="who-you">{t("Vous","You")}</span><span class="who-codem">CODEM</span><span class="who-tbd">{t("À préciser","To confirm")}</span></span></li>' for a,c,code in GRID)
 data=' '.join(f'data-f{i}="{f}|{t(*DESC[i])}|{SLUGS[i]}"' for i,f in enumerate(FORMULES))
 ticks=''.join(f'<span>{f}</span>' for f in FORMULES)
 return f'''<section class="section band-sand formula-tool" aria-labelledby="ft-title"><div class="wrap ft-grid"><div class="ft-left">{eyebrow('Trouvez votre formule','Find your package')}<h2 id="ft-title">{t('Ce que vous faites.<br><em>Ce que CODEM fait.</em>','What you do.<br><em>What CODEM does.</em>')}</h2><p class="subtle">{t('Faites glisser le curseur : les tâches passent de votre côté à celui de CODEM.','Slide the cursor: tasks move from your side to CODEM’s.')}</p><div class="ft-control" {data}><label for="ft-range" class="sr-only">{t('Niveau de prise en charge','Level of service')}</label><input id="ft-range" type="range" min="0" max="4" step="1" value="2"><div class="ft-ticks" aria-hidden="true">{ticks}</div></div><div class="ft-result" aria-live="polite"><span class="ft-name">Confort</span><p class="ft-desc"></p><p class="ft-count"><strong data-count>0</strong> {t('tâches sur 10 prises en charge par CODEM','of 10 tasks handled by CODEM')}</p><a class="btn btn-cta btn-lg ft-cta" href="{url('devis')}?service=particulier&amp;formule=confort">{t('Demander un devis','Get a quote')} <span class="ft-cta-name">Confort</span></a></div></div><ul class="ft-tasks">{rows}</ul></div><p class="wrap fine-print">{t('Grille établie d’après la brochure CODEM ; le contenu exact de votre formule est confirmé dans le devis.','Grid based on the CODEM brochure; the exact scope of your package is confirmed in your quote.')}</p></section>'''

def gallery():
 shots=[('ancien-02','La flotte CODEM en intervention','The CODEM fleet on a job'),('ancien-12','Les camions CODEM','CODEM trucks'),('ancien-21','Monte-meubles en place','Furniture lift in position'),('ancien-33','Mobilier protégé dans le camion','Protected furniture in the truck'),('ancien-14','Chaises de caractère emballées','Period chairs wrapped'),('ancien-29','Meuble ancien manipulé avec soin','Antique furniture handled with care')]
 cards=''.join(f'<figure class="hs-card">{img(i,t(a,c))}<figcaption><span>0{k+1}</span>{t(a,c)}</figcaption></figure>' for k,(i,a,c) in enumerate(shots))
 return f'''<section class="hscroll band-navy" aria-labelledby="hs-title"><div class="hs-sticky"><div class="wrap hs-head">{eyebrow('En images','In pictures')}<h2 id="hs-title">{t('Des gestes précis,<br><em>du premier carton au dernier.</em>','Careful hands,<br><em>from first box to last.</em>')}</h2></div><div class="hs-track">{cards}<div class="hs-card hs-end"><p>{t('Votre déménagement peut être le prochain.','Your move could be next.')}</p><a class="btn btn-cta" href="{url('devis')}?service=particulier">{t('Demander un devis','Get a quote')}</a></div></div></div></section>'''

def particuliers_body():
 europe=f'''<section class="section band-glacier"><div class="wrap europe-teaser"><div class="image-wrap">{img('ancien-12',t('Camions CODEM prêts pour un long trajet','CODEM trucks ready for a long journey'))}</div><div>{eyebrow('France et Europe','France and Europe')}<h2>{t('Une autre ville,<br><em>un autre pays.</em>','Another city,<br><em>another country.</em>')}</h2><p>{t('Espagne, Portugal, Italie ou ailleurs : CODEM étudie le trajet, le volume et les accès avant de vous proposer une solution.','Spain, Portugal, Italy or elsewhere: CODEM reviews the route, volume and access before proposing a solution.')}</p>{link('europe',t('Préparer un départ à l’étranger','Plan a move abroad'),'btn outline')}</div></div></section>'''
 return acts()+formula_slider()+gallery()+europe+f'<section class="section band-ivory"><div class="wrap faq-grid"><div>{eyebrow("Vos questions","Your questions")}<h2>{t("Avant de faire<br><em>vos cartons.</em>","Before you<br><em>start packing.</em>")}</h2></div><div>{faqs()}</div></div></section>'+cta(t('Commencez quand<br><em>vous êtes prêt.</em>','Start whenever<br><em>you’re ready.</em>'))
