"""Pages intérieures « en mouvement » (lot 2 : prototype Particuliers)."""
import build as b
from build import t,url,link,img,eyebrow,cta,faqs
from v1content import GRID,FORMULES

def scene_svg():
 box=lambda x,y,w=70,h=56,cls='box':f'<g class="{cls}"><rect x="{x}" y="{y}" width="{w}" height="{h}" rx="3" fill="#c99a62"/><rect x="{x}" y="{y}" width="{w}" height="10" fill="#b4834d"/><rect x="{x+w/2-5}" y="{y}" width="10" height="{h}" fill="#e8d3b0"/></g>'
 wrapped=lambda x,y,w=70,h=56:f'<g><rect x="{x-3}" y="{y-3}" width="{w+6}" height="{h+6}" rx="6" fill="#dbeefa" opacity=".9"/>'+''.join(f'<circle cx="{x+6+i*14}" cy="{y+8+j*14}" r="4" fill="#ffffff" opacity=".8"/>' for i in range(int(w/14)) for j in range(int(h/14)))+f'<rect x="{x+8}" y="{y+h/2-8}" width="{w-16}" height="16" rx="2" fill="#e04b3c"/><text x="{x+w/2}" y="{y+h/2+4}" text-anchor="middle" font-size="10" font-weight="700" fill="#fff" font-family="Arial">FRAGILE</text></g>'
 sofa=lambda x,y,c='#5f6b9a':f'<g><rect x="{x}" y="{y+20}" width="150" height="46" rx="10" fill="{c}"/><rect x="{x+8}" y="{y}" width="134" height="34" rx="10" fill="{c}" opacity=".85"/><rect x="{x-8}" y="{y+16}" width="22" height="50" rx="8" fill="{c}"/><rect x="{x+136}" y="{y+16}" width="22" height="50" rx="8" fill="{c}"/><rect x="{x+6}" y="{y+66}" width="8" height="10" fill="#3a3f5c"/><rect x="{x+136}" y="{y+66}" width="8" height="10" fill="#3a3f5c"/></g>'
 plant=lambda x,y:f'<g><rect x="{x}" y="{y+40}" width="30" height="30" rx="4" fill="#22264f"/><ellipse cx="{x+8}" cy="{y+28}" rx="10" ry="22" fill="#5fb03a" transform="rotate(-20 {x+8} {y+28})"/><ellipse cx="{x+22}" cy="{y+24}" rx="10" ry="24" fill="#2f7d1e" transform="rotate(18 {x+22} {y+24})"/></g>'
 truck='''<g class="truck"><rect x="0" y="0" width="230" height="120" rx="8" fill="#ffffff" stroke="#d8dce6" stroke-width="2"/><text x="115" y="72" text-anchor="middle" font-family="Georgia" font-size="40" fill="#22264f" letter-spacing="2">C<tspan fill="#5fb03a">O</tspan>DEM</text><rect x="230" y="34" width="70" height="86" rx="10" fill="#ffffff" stroke="#d8dce6" stroke-width="2"/><path d="M262 42 h28 a6 6 0 0 1 6 6 v26 h-34z" fill="#bfe0f2"/><rect x="0" y="112" width="300" height="10" fill="#22264f"/><circle cx="60" cy="128" r="18" fill="#22264f"/><circle cx="60" cy="128" r="7" fill="#d8dce6"/><circle cx="250" cy="128" r="18" fill="#22264f"/><circle cx="250" cy="128" r="7" fill="#d8dce6"/></g>'''
 return f'''<svg class="scene" viewBox="0 0 600 460" role="img" aria-label="{t('Illustration des quatre étapes d’un déménagement','Illustration of the four stages of a move')}">
<defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#eaf2f8"/><stop offset="1" stop-color="#f7f4ee"/></linearGradient></defs>
<rect width="600" height="460" rx="28" fill="url(#sky)"/>
<g class="layer act-1"><rect x="40" y="70" width="520" height="300" rx="10" fill="#f3ede3"/><rect x="380" y="100" width="120" height="90" rx="6" fill="#ffffff" stroke="#e1d8c8" stroke-width="6"/><line x1="440" y1="100" x2="440" y2="190" stroke="#e1d8c8" stroke-width="4"/>{sofa(70,240)}{plant(480,290)}{box(270,300)}{box(345,300)}{box(305,248)}</g>
<g class="layer act-2"><rect x="40" y="70" width="520" height="300" rx="10" fill="#f3ede3"/>{sofa(70,240,'#9aa5c4')}<path d="M62 250 q80 -30 166 0 v86 h-166z" fill="#cfd6e6" opacity=".85"/>{wrapped(270,300)}{wrapped(345,300)}{wrapped(305,248)}<g class="tape"><circle cx="470" cy="330" r="26" fill="#d9a84c"/><circle cx="470" cy="330" r="12" fill="#f3ede3"/></g></g>
<g class="layer act-3"><rect x="0" y="372" width="600" height="88" fill="#d8dee8"/><g class="road">{''.join(f'<rect x="{x}" y="412" width="40" height="6" rx="3" fill="#ffffff"/>' for x in range(10,600,80))}</g><g class="truck-move" transform="translate(140 230)">{truck}</g><circle cx="80" cy="120" r="34" fill="#ffd27a" opacity=".7"/></g>
<g class="layer act-4"><path d="M170 190 L300 100 L430 190 Z" fill="#22264f"/><rect x="190" y="188" width="220" height="182" fill="#ffffff" stroke="#e1d8c8" stroke-width="3"/><rect x="282" y="290" width="44" height="80" rx="4" fill="#5fb03a"/><rect x="214" y="220" width="46" height="40" rx="4" fill="#bfe0f2"/><rect x="342" y="220" width="46" height="40" rx="4" fill="#bfe0f2"/>{plant(120,300)}{box(440,318,60,48)}<g class="badge"><circle cx="470" cy="140" r="36" fill="#5fb03a"/><path d="M452 140 l12 12 l22 -24" fill="none" stroke="#14163f" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></g></g>
</svg>'''

ACTS=[('Acte 1','Act 1','Vous nous racontez votre projet.','You tell us about your move.','Départ, arrivée, période, type de logement : quelques minutes suffisent. Un conseiller étudie le volume et les accès, et organise une visite lorsque c’est utile.','From, to, dates, type of home: a few minutes are enough. An adviser reviews volume and access, and arranges a visit when useful.',['Devis gratuit, sans engagement','Visite à domicile ou à distance'],['Free, no-obligation quote','Home or video survey']),
 ('Acte 2','Act 2','Nous protégeons ce qui compte.','We protect what matters.','Cartons, papier bulle, housses pour matelas et sommiers, protections pour télévisions, miroirs et tableaux, penderies pour les vêtements sur cintres.','Boxes, bubble wrap, mattress covers, protection for TVs, mirrors and artwork, wardrobe boxes for hanging clothes.',['Emballage du fragile selon la formule','Fourniture des emballages'],['Fragile packing depending on package','Packing materials supplied']),
 ('Acte 3','Act 3','Nous chargeons, nous roulons.','We load, we drive.','Démontage du mobilier, manutention et transport en véhicules capitonnés, adaptés à votre volume. Monte-meubles prévu si l’escalier ne suffit pas.','Furniture dismantling, handling and transport in padded vehicles matched to your volume. A furniture lift is arranged if the stairs are not enough.',['Véhicules capitonnés','Monte-meubles si nécessaire'],['Padded vehicles','Furniture lift if needed']),
 ('Acte 4','Act 4','Vous êtes chez vous.','You are home.','Remontage et mise en place du mobilier, déballage selon votre formule. L’équipe fait le point avec vous avant de partir.','Furniture reassembled and placed, unpacking depending on your package. The team checks everything with you before leaving.',['Remontage et mise en place','Déballage selon la formule'],['Reassembly and placement','Unpacking depending on package'])]

def acts():
 steps=''
 for i,(a,a2,h,h2,p,p2,l,l2) in enumerate(ACTS):
  items=''.join(f'<li>{t(x,y)}</li>' for x,y in zip(l,l2))
  steps+=f'<article class="act" data-act="{i+1}"><span class="act-num">{t(a,a2)}</span><h3>{t(h,h2)}</h3><p>{t(p,p2)}</p><ul class="act-list">{items}</ul></article>'
 dots=''.join(f'<span class="act-dot" data-dot="{i+1}"></span>' for i in range(4))
 return f'''<section class="acts band-ivory" aria-labelledby="acts-title"><div class="wrap"><div class="acts-head">{eyebrow('Comment ça se passe','How it works')}<h2 id="acts-title">{t('Votre déménagement<br><em>en quatre actes.</em>','Your move<br><em>in four acts.</em>')}</h2></div><div class="acts-grid"><div class="acts-stage"><div class="acts-sticky" data-act-stage="1">{scene_svg()}<div class="act-progress">{dots}</div></div></div><div class="acts-text">{steps}<div class="act-cta"><a class="btn btn-cta btn-lg" href="{url('devis')}?service=particulier">{t('Commencer mon devis','Start my quote')}</a></div></div></div></div></section>'''

DESC=[('Vous préparez vos cartons. CODEM protège, charge, transporte.','You pack your boxes. CODEM protects, loads and transports.'),('CODEM ajoute le démontage, le remontage et la mise en place du mobilier.','CODEM adds furniture dismantling, reassembly and placement.'),('CODEM emballe aussi le fragile et fournit les emballages.','CODEM also packs fragile items and supplies packing materials.'),('CODEM emballe tout. Vous ne déballez que le non-fragile.','CODEM packs everything. You only unpack non-fragile items.'),('CODEM s’occupe de tout, jusqu’au dernier carton déballé.','CODEM handles everything, down to the last box unpacked.')]
SLUGS=['self','self-plus','confort','confort-plus','grand-confort']
def formula_slider():
 rows=''.join(f'<li class="task" data-codes="{code}"><span class="task-name">{t(a,c)}</span><span class="who" aria-live="off"><span class="who-you">{t("Vous","You")}</span><span class="who-codem">CODEM</span><span class="who-tbd">{t("À préciser","To confirm")}</span></span></li>' for a,c,code in GRID)
 data=' '.join(f'data-f{i}="{f}|{t(*DESC[i])}|{SLUGS[i]}"' for i,f in enumerate(FORMULES))
 ticks=''.join(f'<span>{f}</span>' for f in FORMULES)
 return f'''<section class="section band-sand formula-tool" aria-labelledby="ft-title"><div class="wrap ft-grid"><div class="ft-left">{eyebrow('Trouvez votre formule','Find your package')}<h2 id="ft-title">{t('Ce que vous faites.<br><em>Ce que CODEM fait.</em>','What you do.<br><em>What CODEM does.</em>')}</h2><p class="subtle">{t('Faites glisser le curseur : les tâches passent de votre côté à celui de CODEM.','Slide the cursor: tasks move from your side to CODEM’s.')}</p><div class="ft-control" {data}><label for="ft-range" class="sr-only">{t('Niveau de prise en charge','Level of service')}</label><input id="ft-range" type="range" min="0" max="4" step="1" value="2"><div class="ft-ticks" aria-hidden="true">{ticks}</div></div><div class="ft-result" aria-live="polite"><span class="ft-name">Confort</span><p class="ft-desc"></p><p class="ft-count"><strong data-count>0</strong> {t('tâches sur 10 prises en charge par CODEM','of 10 tasks handled by CODEM')}</p><a class="btn btn-cta btn-lg ft-cta" href="{url('devis')}?service=particulier&amp;formule=confort">{t('Demander un devis','Get a quote')} <span class="ft-cta-name">Confort</span></a></div></div><ul class="ft-tasks">{rows}</ul></div><p class="wrap fine-print">{t('Grille établie d’après la brochure CODEM ; le contenu exact de votre formule est confirmé dans le devis.','Grid based on the CODEM brochure; the exact scope of your package is confirmed in your quote.')}</p></section>'''

def gallery():
 shots=[('ancien-13','Préparer les cartons','Preparing boxes'),('ancien-10','Mobilier protégé','Protected furniture'),('ancien-19','Chargement devant une maison','Loading outside a house'),('ancien-03','Le camion prêt au départ','The truck ready to go'),('ancien-27','Le fragile, signalé','Fragile, clearly marked'),('ancien-07','Arrivée chez soi','Arriving home')]
 cards=''.join(f'<figure class="hs-card">{img(i,t(a,c))}<figcaption><span>0{k+1}</span>{t(a,c)}</figcaption></figure>' for k,(i,a,c) in enumerate(shots))
 return f'''<section class="hscroll band-navy" aria-labelledby="hs-title"><div class="hs-sticky"><div class="wrap hs-head">{eyebrow('En images','In pictures')}<h2 id="hs-title">{t('Des gestes précis,<br><em>du premier carton au dernier.</em>','Careful hands,<br><em>from first box to last.</em>')}</h2></div><div class="hs-track">{cards}<div class="hs-card hs-end"><p>{t('Votre déménagement peut être le prochain.','Your move could be next.')}</p><a class="btn btn-cta" href="{url('devis')}?service=particulier">{t('Demander un devis','Get a quote')}</a></div></div></div></section>'''

def particuliers_body():
 europe=f'''<section class="section band-glacier"><div class="wrap europe-teaser"><div class="et-route" aria-hidden="true"><svg viewBox="0 0 520 160"><path class="draw" d="M20 120 C140 20 300 20 500 70" fill="none" stroke="#22264f" stroke-width="3" stroke-dasharray="8 10"/><circle cx="20" cy="120" r="10" fill="#5fb03a"/><circle cx="500" cy="70" r="10" fill="#22264f"/><text x="20" y="152" font-size="14" fill="#22264f" font-family="Arial">Nogent-sur-Marne</text><text x="420" y="50" font-size="14" fill="#22264f" font-family="Arial">{t('Votre destination','Your destination')}</text></svg></div><div>{eyebrow('France et Europe','France and Europe')}<h2>{t('Une autre ville,<br><em>un autre pays.</em>','Another city,<br><em>another country.</em>')}</h2><p>{t('Espagne, Portugal, Italie ou ailleurs : CODEM étudie le trajet, le volume et les accès avant de vous proposer une solution.','Spain, Portugal, Italy or elsewhere: CODEM reviews the route, volume and access before proposing a solution.')}</p>{link('europe',t('Préparer un départ à l’étranger','Plan a move abroad'),'btn outline')}</div></div></section>'''
 return acts()+formula_slider()+gallery()+europe+f'<section class="section band-ivory"><div class="wrap faq-grid"><div>{eyebrow("Vos questions","Your questions")}<h2>{t("Avant de faire<br><em>vos cartons.</em>","Before you<br><em>start packing.</em>")}</h2></div><div>{faqs()}</div></div></section>'+cta(t('Commencez quand<br><em>vous êtes prêt.</em>','Start whenever<br><em>you’re ready.</em>'))
