import build as b
from build import t,label,url,link,img,video,toggle,eyebrow,actions,cta,steps,faqs,PHONE,PHONE_HREF

# Adresse de réception des demandes (e-mail, CRM ou fonction serveur).
# Laisser vide tant que CODEM n'a pas fourni de destination : aucune donnée n'est alors transmise.
FORM_ENDPOINT='https://hzeohzbdckhehbkjxxws.supabase.co/rest/v1/demandes'

def crumb(key):return f'<div class="wrap breadcrumbs">{link("home")} &nbsp; / &nbsp; {label(key)}</div>'
def field(name,fr,en,kind='text',required=False,options=None,full=False,value='',attrs='',fid=None):
 lab=t(fr,en);fid=fid or name;rid=f'{fid}-error';req=' required' if required else '';common=f'id="{fid}" name="{name}" aria-describedby="{rid}"{req} {attrs}'.rstrip()
 if options:control=f'<select {common}>'+''.join(f'<option value="{v}"{" selected" if v==value else ""}>{t(a,c)}</option>' for v,a,c in options)+'</select>'
 elif kind=='textarea':control=f'<textarea {common} rows="4" maxlength="4000"></textarea>'
 else:control=f'<input {common} type="{kind}"'+(f' value="{value}"' if value else '')+(' min="0"' if kind=='number' else '')+(' autocomplete="name"' if name in ['nom','prenom'] else ' autocomplete="email"' if kind=='email' else ' autocomplete="tel"' if kind=='tel' else '')+'>'
 return f'<div class="field {"full" if full else ""}"><label for="{fid}">{lab}<span data-required>{" *" if required else ""}</span></label>{control}<span class="field-error" id="{rid}"></span></div>'
def check(name,fr,en,value='oui',required=False):
 return f'<label class="check"><input type="checkbox" name="{name}" value="{value}"{" required" if required else ""}><span>{t(fr,en)}</span></label>'
SELECT=('','Sélectionner','Select')
FILE_ATTRS='multiple accept="image/*,video/*"'
def status_msg():return f'<p class="form-status" role="status" aria-live="polite"></p>'
def privacy(short=False):return f'<p class="fine-print">{t("Vos informations servent uniquement à étudier votre projet et à vous recontacter.","Your information is used only to assess your move and contact you.")} {link("privacy",t("Politique de confidentialité","Privacy policy"))}.</p><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div>'
SLOTS=[SELECT,('matin','Matin 9 h – 12 h','Morning 9 am – 12 pm'),('apres-midi','Après-midi 13 h – 18 h','Afternoon 1 pm – 6 pm'),('vendredi','Vendredi 13 h – 17 h','Friday 1 pm – 5 pm'),('a-convenir','À convenir','To be agreed')]
HOURS=lambda:f'<dl class="hours"><dt>{t("Lundi – jeudi","Monday – Thursday")}</dt><dd>9 h – 12 h · 13 h – 18 h</dd><dt>{t("Vendredi","Friday")}</dt><dd>{t("jusqu’à 17 h","until 5 pm")}</dd><dt>{t("Week-end","Weekend")}</dt><dd>{t("Fermé","Closed")}</dd></dl>'
LANGS=lambda:t('Français · Anglais · Espagnol · Portugais','French · English · Spanish · Portuguese')

def contact():
 rappel=f'''<form class="form-box mini-form" id="callback-form" data-kind="rappel" data-endpoint="{FORM_ENDPOINT}" novalidate><span class="eyebrow">{t('Rappel','Callback')}</span><h2>{t('Demander un rappel','Request a callback')}</h2><div class="fields one">{field('prenom','Prénom','First name',required=True,fid='cb-prenom')}{field('telephone','Téléphone','Phone',kind='tel',required=True,fid='cb-tel')}{field('creneau','Créneau','Time slot',options=SLOTS,fid='cb-slot')}</div>{privacy()}<button class="btn btn-cta" type="submit">{t('Être rappelé','Call me back')}</button>{status_msg()}</form>'''
 visite=f'''<form class="form-box mini-form" id="visit-form" data-kind="visite" data-endpoint="{FORM_ENDPOINT}" novalidate><span class="eyebrow">{t('Rendez-vous','Appointment')}</span><h2>{t('Demander une visite','Request a survey visit')}</h2><div class="fields one">{field('type','Type de visite','Visit type',options=[('domicile','À domicile','At your home'),('distance','À distance (vidéo)','Remote (video)')],fid='vi-type')}{field('email','E-mail','Email',kind='email',required=True,fid='vi-email')}{field('telephone','Téléphone','Phone',kind='tel',fid='vi-tel')}{field('creneau','Créneau souhaité','Preferred slot',kind='datetime-local',fid='vi-slot')}</div>{privacy()}<button class="btn btn-cta" type="submit">{t('Demander la visite','Request the visit')}</button>{status_msg()}</form>'''
 message=f'''<form class="form-box" id="contact-form" data-kind="message" data-endpoint="{FORM_ENDPOINT}" novalidate><span class="eyebrow">{t('Message','Message')}</span><h2>{t('Écrire à CODEM','Write to CODEM')}</h2><div class="fields">{field('nom','Nom complet','Full name',required=True)}{field('preference','Contact préféré','Preferred contact',options=[('telephone','Téléphone','Phone'),('email','E-mail','Email')])}{field('telephone','Téléphone','Phone',kind='tel')}{field('email','Adresse e-mail','Email address',kind='email')}{field('projet','Type de projet','Project type',options=[('particulier','Particulier','Home move'),('succession','Succession','Estate clearance'),('entreprise','Entreprise','Business move'),('stockage','Garde-meubles','Storage'),('monte-meubles','Monte-meubles','Furniture lift'),('autre','Autre besoin','Other enquiry')])}{field('periode','Période souhaitée','Preferred dates')}{field('depart','Ville de départ','Moving from')}{field('arrivee','Ville d’arrivée','Moving to')}{field('message','Votre message','Your message',kind='textarea',full=True)}</div>{check('consentement','J’accepte que mes données soient utilisées pour traiter ma demande.','I agree to my data being used to handle my enquiry.',required=True)}{privacy()}<button class="btn btn-cta" type="submit">{t('Envoyer mon message','Send my message')}</button>{status_msg()}</form>'''
 return crumb('contact')+f'''<section class="section band-ivory" style="padding-top:30px"><div class="wrap contact-grid"><div>{eyebrow('Faisons connaissance','Let’s talk')}<h1 style="font-size:clamp(3rem,5vw,5.2rem)">{t('Parlons de votre<br><em>déménagement.</em>','Let’s talk about<br><em>your move.</em>')}</h1><p class="lead">{t('Appelez CODEM, demandez un rappel ou préparez une visite à domicile ou à distance.','Call CODEM, request a callback or arrange a home or video survey.')}</p><div class="actions">{link('devis',t('Demander un devis','Request a quote'),'btn btn-cta')}<a class="btn outline" href="{PHONE_HREF}">{t('Appeler','Call')} {PHONE}</a></div></div><div class="contact-card"><div class="image-wrap contact-visual">{img("camion-chauffeur",t("Camion CODEM","CODEM truck"))}</div><span class="eyebrow">CODEM Déménagements</span><p class="contact-phones"><a href="{PHONE_HREF}">{PHONE}</a><a href="tel:+33667570912">06 67 57 09 12</a></p><p>39 boulevard de Strasbourg<br>94130 Nogent-sur-Marne</p><p class="open-badge" data-open hidden></p><h3>{t('Horaires','Opening hours')}</h3>{HOURS()}<h3>{t('Langues parlées','Languages spoken')}</h3><p>{LANGS()}</p></div></div></section><section class="section band-sand" id="rappel"><div class="wrap">{eyebrow('Choisissez votre échange','Choose how to talk')}<h2>{t('Un formulaire court<br><em>quand vous en avez besoin.</em>','A short form<br><em>when you need it.</em>')}</h2><div class="two-forms inset">{rappel}{visite}</div></div></section><section class="section band-ivory" id="ecrire"><div class="wrap narrow-form">{message}</div></section>{cta()}'''

STEPS=[('Projet','Project'),('Trajet','Route'),('Calendrier','Schedule'),('Lieux','Properties'),('Volume','Volume'),('Prestations','Services'),('Pièces','Items'),('Coordonnées','Your details'),('Confirmation','Confirmation')]
PROJECTS=[('particulier','Particulier','Home move','Appartement, maison, changement de ville.','Flat, house, new town.'),('succession','Succession','Estate clearance','Logement à vider ou à partager.','A home to clear or share out.'),('entreprise','Entreprise','Business','Bureaux, archives, informatique.','Offices, records, IT.'),('stockage','Stockage','Storage','Garde-meubles court ou long terme.','Short or long-term storage.'),('monte-meubles','Monte-meubles','Furniture lift','Étages, fenêtres, accès difficiles.','Upper floors, windows, tight access.'),('objet-specialise','Objet spécialisé','Specialist item','Piano, œuvre d’art, objet lourd.','Piano, artwork, heavy item.')]
FORMULES=[('self','Self','Self'),('self-plus','Self plus','Self plus'),('confort','Confort','Confort'),('confort-plus','Confort plus','Confort plus'),('grand-confort','Grand Confort','Grand Confort'),('a-definir','À définir avec CODEM','To be agreed with CODEM')]
def step(i,title_fr,title_en,body,lead=''):
 hidden='' if i==0 else ' hidden'
 return f'<section class="qstep" data-step="{i}"{hidden} aria-labelledby="qstep-title-{i}"><span class="eyebrow">{t("Étape","Step")} {i+1}</span><h2 id="qstep-title-{i}" tabindex="-1">{t(title_fr,title_en)}</h2>{lead}{body}</section>'
def place(side,fr,en):
 types=[SELECT,('appartement','Appartement','Flat'),('maison','Maison','House'),('bureaux','Bureaux ou local','Office or premises'),('stockage','Stockage','Storage unit'),('autre','Autre','Other')]
 return f'<fieldset class="panel"><legend>{t(fr,en)}</legend><div class="fields">'+field(f'{side}_type','Type de logement ou local','Property type',options=types,full=True)+field(f'{side}_etage','Étage','Floor')+field(f'{side}_ascenseur','Ascenseur','Lift',options=[SELECT,('oui','Oui','Yes'),('non','Non','No'),('a-verifier','À vérifier','To check')])+field(f'{side}_portage','Portage estimé (mètres)','Estimated carrying distance (metres)')+field(f'{side}_stationnement','Stationnement','Parking',options=[SELECT,('facile','Facile','Easy'),('a-reserver','À réserver','Needs booking'),('difficile','Difficile','Difficult'),('a-verifier','À vérifier','To check')])+'</div>'+check(f'{side}_rue_etroite','Rue étroite ou accès contraint','Narrow street or restricted access')+'</fieldset>'
def quote():
 CUR=' aria-current="step"'
 nav=''.join(f'<li data-nav="{i}"{CUR if i==0 else ""}><span class="dot">{i+1}</span>{t(a,c)}</li>' for i,(a,c) in enumerate(STEPS))
 cards=''.join(f'<label class="choice-card"><input type="radio" name="projet" value="{v}" required><span class="choice-title">{t(a,c)}</span><span class="choice-sub">{t(d,e)}</span></label>' for v,a,c,d,e in PROJECTS)
 s=[]
 s.append(step(0,'Projet','Project',f'<fieldset><legend class="question">{t("Quel projet souhaitez-vous préparer ?","What would you like to plan?")}</legend><div class="choice-grid">{cards}</div><span class="field-error" id="projet-error"></span></fieldset>'))
 s.append(step(1,'Trajet','Route',f'<fieldset class="panel"><legend>{t("Lieu de départ","Collection")}</legend><div class="fields">{field("depart_commune","Commune de départ","Collection town",required=True)}{field("depart_pays","Pays de départ","Collection country",value="France")}</div></fieldset><fieldset class="panel"><legend>{t("Lieu d’arrivée","Delivery")}</legend><div class="fields">{field("arrivee_commune","Commune ou destination d’arrivée","Delivery town or destination",required=True)}{field("arrivee_pays","Pays d’arrivée","Delivery country",value="France")}</div></fieldset>{check("groupage","Je souhaite étudier une option de groupage","I would like to consider a shared-load option")}<p class="fine-print">{t("La commune et le pays suffisent à ce stade. Les adresses précises pourront être ajoutées après l’étude initiale.","Town and country are enough for now. Exact addresses can be added after the initial review.")}</p>'))
 s.append(step(2,'Calendrier','Schedule',f'<div class="fields one">{field("date","Date souhaitée","Preferred date",kind="date",attrs="data-min-today")}{field("flexibilite","Flexibilité","Flexibility",options=[SELECT,("fixe","Date fixe","Fixed date"),("3-jours","Plus ou moins 3 jours","Give or take 3 days"),("1-semaine","Plus ou moins 1 semaine","Give or take 1 week"),("a-definir","À définir","To be decided")])}</div>{check("urgent","Le projet est urgent","This is urgent")}<div class="fields one">{field("contraintes","Contraintes horaires (facultatif)","Timing constraints (optional)",kind="textarea")}</div>'))
 s.append(step(3,'Lieux','Properties',place('depart','Au départ','At collection')+place('arrivee','À l’arrivée','At delivery')))
 s.append(step(4,'Volume','Volume',f'<div class="segmented" role="radiogroup" aria-label="{t("Mode d’estimation","Estimate method")}"><label><input type="radio" name="volume_mode" value="surface" checked><span>{t("Par surface","By floor area")}</span></label><label><input type="radio" name="volume_mode" value="volume"><span>{t("Volume déjà estimé","Volume already estimated")}</span></label></div><div class="fields one"><div data-mode="surface">{field("surface","Surface approximative en m²","Approximate floor area in m²",kind="number")}</div><div data-mode="volume" hidden>{field("volume","Volume estimé en m³","Estimated volume in m³",kind="number")}</div>{field("taille","Taille du logement","Property size",options=[SELECT,("studio","Studio / T1","Studio / 1 room"),("t2-t3","T2 – T3","2 – 3 rooms"),("t4","T4 et plus","4 rooms or more"),("maison","Maison","House"),("inconnu","Je ne sais pas","I don’t know")])}{field("annexes","Cave, grenier, extérieur ou cartons (facultatif)","Cellar, attic, outdoor items or boxes (optional)",kind="textarea")}</div><div class="notice"><strong>{t("Aucun tarif automatique","No automatic price")}</strong><br>{t("Votre surface ou votre estimation est transmise au conseiller, qui confirme le volume avec vous, si besoin lors d’une visite.","Your floor area or estimate goes to an adviser, who confirms the volume with you, with a visit if needed.")}</div>'))
 prest=[('emballage','Emballage','Packing'),('demontage','Démontage / remontage','Dismantling / reassembly'),('fragiles','Objets fragiles','Fragile items'),('monte-meubles','Monte-meubles','Furniture lift'),('garde-meubles','Garde-meubles','Storage'),('cartons','Cartons','Boxes')]
 s.append(step(5,'Prestations','Services',f'<div class="fields one">{field("formule","Formule pressentie","Preferred package",options=[SELECT]+FORMULES)}</div><p class="fine-print">{link("formules",t("Comparer les cinq formules","Compare the five packages"))}</p><fieldset><legend class="question">{t("Ce que vous souhaitez nous confier","What you would like us to handle")}</legend><div class="check-grid">'+''.join(check("prestations",a,c,v) for v,a,c in prest)+'</div></fieldset>'))
 s.append(step(6,'Pièces','Items',f'<div class="fields one">{field("objets","Liste d’objets ou informations utiles (facultatif)","List of items or useful details (optional)",kind="textarea")}{field("fichiers","Photos ou courte vidéo (facultatif)","Photos or a short video (optional)",kind="file",attrs=FILE_ATTRS)}</div><p class="fine-print">{t("Des photos des pièces et des accès aident le conseiller à préparer une proposition juste. Jusqu’à 8 fichiers, 25 Mo maximum chacun.","Photos of rooms and access help the adviser prepare an accurate proposal. Up to 8 files, 25 MB each.")}</p>'))
 s.append(step(7,'Coordonnées','Your details',f'<div class="fields one">{field("nom","Nom","Name",required=True)}{field("organisation","Organisation (facultatif)","Organisation (optional)")}{field("email","E-mail","Email",kind="email")}{field("telephone","Téléphone","Phone",kind="tel")}{field("canal","Canal préféré","Preferred channel",options=[SELECT,("telephone","Téléphone","Phone"),("email","E-mail","Email")])}{field("creneau","Créneau de rappel","Callback slot",options=SLOTS)}</div>{check("consentement","J’accepte que mes données soient utilisées pour traiter ma demande de devis.","I agree to my data being used to handle my quote request.",required=True)}<span class="field-error" id="consentement-error"></span>{check("marketing","J’accepte de recevoir des informations commerciales (facultatif).","I agree to receive marketing information (optional).")}{privacy()}'))
 s.append(f'<section class="qstep" data-step="8" hidden aria-labelledby="qstep-title-8"><span class="eyebrow">{t("Étape","Step")} 9</span><h2 id="qstep-title-8" tabindex="-1">{t("Confirmation","Confirmation")}</h2><div class="confirm"><div class="confirm-icon" aria-hidden="true">✓</div><h3 data-confirm-title>{t("Votre demande est prête","Your request is ready")}</h3><p>{t("Numéro de demande :","Request number:")} <strong data-ref></strong></p><p data-confirm-text></p><div class="summary" data-summary></div><div class="actions center">{link("contact",t("Demander une visite","Request a survey visit"),"btn","data-visit-link")}<a class="btn outline" href="{PHONE_HREF}">{t("Appeler","Call")} {PHONE}</a></div></div></section>')
 errbox=f'<div class="error-summary" role="alert" hidden><strong>{t("Vérifiez ces informations","Please check these details")}</strong><ul></ul></div>'
 return f'''<section class="quote-page"><div class="wrap quote-shell"><aside class="quote-side"><span class="eyebrow">{t('Demande de devis','Quote request')}</span><p class="quote-count">{t('Étape','Step')} <span data-step-num>1</span> {t('sur','of')} 9</p><ol class="quote-steps">{nav}</ol><p class="quote-note">{t('Enregistré sur cet appareil. Vos réponses sont conservées lorsque vous revenez en arrière.','Saved on this device. Your answers are kept when you go back.')}</p><a class="quote-help" href="{PHONE_HREF}">{t('Besoin d’aide ?','Need help?')} <strong>{PHONE}</strong></a></aside><form class="quote-card" id="quote-form" data-endpoint="{FORM_ENDPOINT}" novalidate><h1 class="sr-only">{t('Demande de devis','Quote request')}</h1><div class="progress-track"><div class="progress-bar"></div></div>{errbox}{''.join(s)}<div class="quote-actions"><button class="btn outline" type="button" data-prev>{t('Quitter','Exit')}</button><button class="btn" type="button" data-next>{t('Continuer','Continue')}</button><button class="btn" type="submit" data-submit hidden>{t('Envoyer la demande','Send my request')}</button></div>{status_msg()}</form></div></section>'''

if __name__=='__main__':
 for lang in ['fr','en']:
  b.LANG=lang;b.write('contact',contact(),t('Contactez CODEM Déménagements à Nogent-sur-Marne : téléphone, demande de rappel, visite à domicile ou à distance, horaires et langues parlées.','Contact CODEM Moving in Nogent-sur-Marne: phone, callback request, home or video survey, opening hours and languages spoken.'));b.write('devis',quote(),t('Demandez votre devis de déménagement CODEM en 9 étapes : trajet, dates, accès, volume, prestations et photos. Un conseiller étudie votre demande.','Request your CODEM moving quote in 9 steps: route, dates, access, volume, services and photos. An adviser reviews your request.'))
