"""Contenus métier repris de la version précédente du site (V1) et intégrés au design premium."""
import build as b
from build import t,label,url,link,eyebrow,cta_strip

# Type de projet pré-sélectionné dans le devis depuis chaque page service
PROJECT_OF={'particuliers':'particulier','entreprises':'entreprise','europe':'particulier','stockage':'stockage','monte':'monte-meubles','piano':'objet-specialise'}

V1={
'entreprises':dict(
 ess=[('Inventaire du mobilier et des équipements','Inventory of furniture and equipment'),('Marquage et étiquetage','Marking and labelling'),('Transfert d’archives confidentielles','Confidential records transfer'),('Planning adapté à l’activité','Schedule built around your activity')],
 eyebrow=('Transfert professionnel','Business relocation'),title=('Mobilier, dossiers administratifs<br><em>et archives.</em>','Furniture, files<br><em>and records.</em>'),
 paras=[('CODEM dispose du matériel nécessaire pour transporter les biens professionnels en sécurité. L’intervention peut concerner un transfert interne ou un déménagement complet vers un nouveau site.','CODEM has the equipment needed to move business assets safely, whether for an internal transfer or a full move to a new site.'),('Sur demande, l’équipe réalise la mise en cartons des dossiers, le démontage et la protection du mobilier, puis son remontage et sa remise en place. Les transferts d’archives et de documents confidentiels font l’objet d’une manutention attentive.','On request, the team boxes up files, dismantles and protects furniture, then reassembles and places it. Records and confidential documents are handled with particular care.')],
 checks=[('Transferts de sociétés, bureaux et services administratifs','Company, office and administrative relocations'),('Prise en charge du mobilier, des archives et des équipements','Furniture, records and equipment handled'),('Destruction de documents ou mise en déchetterie selon le besoin','Document destruction or waste disposal if needed')],
 steps_title=('Un transfert organisé<br><em>avec précision.</em>','A relocation organised<br><em>with precision.</em>'),
 steps=[('Inventorier','Take inventory','Recensez les postes, le mobilier, les archives, documents et équipements à prendre en charge.','List workstations, furniture, records, documents and equipment to be moved.'),('Planifier','Plan','CODEM prépare le marquage, l’étiquetage et le calendrier afin de limiter l’interruption de votre activité.','CODEM prepares marking, labelling and the schedule to keep disruption to a minimum.'),('Transférer et remettre en place','Move and set up','L’équipe protège, transporte, remonte et remet en place le mobilier selon le périmètre convenu.','The team protects, moves, reassembles and places furniture within the agreed scope.')],
 photo='ancien-16'),
'europe':dict(
 ess=[('Voyages réguliers en Europe','Regular trips across Europe'),('Groupage sur poids lourd','Shared loads on heavy goods vehicles'),('Équipe multilingue','Multilingual team'),('Cinq formules au choix','Five packages to choose from')],
 eyebrow=('Toutes destinations en Europe','All European destinations'),title=('Particuliers, entreprises,<br><em>militaires et mutations.</em>','Households, businesses,<br><em>military and job transfers.</em>'),
 paras=[('CODEM réalise des déménagements nationaux et dans toute l’Europe, avec une expérience particulière des liaisons France – Italie – Espagne – Portugal. L’équipe parle français, portugais, espagnol et anglais, et étudie les possibilités de voyages réguliers ou de groupage.','CODEM handles national moves and moves throughout Europe, with particular experience of France – Italy – Spain – Portugal routes. The team speaks French, Portuguese, Spanish and English, and looks at regular trips or shared loads.'),('Selon la formule retenue, CODEM peut prendre en charge le démontage, l’emballage du mobilier, des tableaux, glaces, lustres et objets fragiles, puis le chargement, le transport et le déballage.','Depending on the package, CODEM can dismantle and pack furniture, artwork, mirrors, chandeliers and fragile items, then load, transport and unpack.')],
 checks=[('Départs réguliers France – Italie – Espagne – Portugal','Regular departures France – Italy – Spain – Portugal'),('Transfert de bureaux, archives et parc informatique','Office, records and IT equipment transfers'),('Garde-meubles possible pendant une absence','Storage available while you are away')],
 steps_title=('Préparer un déménagement<br><em>international.</em>','Preparing an<br><em>international move.</em>'),
 steps=[('Évaluer le volume','Assess the volume','CODEM étudie les biens à prendre en charge et les accès afin de calculer le volume.','CODEM reviews your belongings and access to calculate the volume.'),('Choisir la formule','Choose the package','Self, Self plus, Confort, Confort plus ou Grand Confort permettent d’adapter la répartition des tâches.','Self, Self plus, Confort, Confort plus or Grand Confort let you share the tasks your way.'),('Organiser le trajet','Organise the journey','Dates, destination, groupage et éventuelles formalités sont confirmés avec votre conseiller.','Dates, destination, shared loads and any formalities are confirmed with your adviser.')],
 photo='ancien-12'),
'stockage':dict(
 ess=[('Stockage court ou long terme','Short or long-term storage'),('Mobilier et affaires personnelles','Furniture and personal belongings'),('Box d’archives','Record storage boxes'),('Volume calculé avec CODEM','Volume calculated with CODEM')],
 eyebrow=('Stockage adapté','Suitable storage'),title=('Entreposez vos biens<br><em>pendant un déménagement, des travaux ou une absence.</em>','Store your belongings<br><em>during a move, renovation or time away.</em>'),
 paras=[('Un garde-meubles peut accueillir du mobilier, des affaires personnelles ou des archives lorsque vous partez à l’étranger, emménagez dans un logement plus petit ou réalisez des travaux.','Storage can hold furniture, personal belongings or records when you move abroad, downsize or renovate.'),('CODEM calcule avec vous le volume à stocker et étudie une solution personnalisée selon la durée. Le mode de stockage, la livraison et l’enlèvement peuvent être intégrés à la demande.','CODEM calculates the volume with you and designs a solution for the duration you need. Storage type, collection and delivery can be included in your request.')],
 checks=[('Box de stockage pour particuliers','Storage boxes for households'),('Solutions pour archives professionnelles','Solutions for business records'),('Biens protégés de la poussière et de l’humidité','Belongings protected from dust and damp')],
 steps_title=('Trouver une solution<br><em>de stockage adaptée.</em>','Finding the right<br><em>storage solution.</em>'),
 steps=[('Décrivez les biens','Describe your belongings','Meubles, cartons, archives : indiquez ce qui doit être entreposé.','Furniture, boxes, records: tell us what needs storing.'),('Choisissez la durée et le mode','Choose duration and type','Quelques semaines entre deux logements ou plusieurs mois : précisez votre besoin.','A few weeks between homes or several months: tell us what you need.'),('Organisez l’enlèvement ou la livraison','Arrange collection or delivery','CODEM peut enlever vos biens et les livrer à votre nouvelle adresse.','CODEM can collect your belongings and deliver them to your new address.')],
 photo='stockage'),
'monte':dict(
 ess=[('Technicien spécialisé','Specialist operator'),('Demi-journée ou journée','Half-day or full day'),('Passage par la fenêtre','Access through the window'),('Objets lourds ou volumineux','Heavy or bulky items')],
 eyebrow=('Location de monte-meubles','Furniture lift hire'),title=('Quand l’escalier ou l’ascenseur<br><em>ne suffit pas.</em>','When the stairs or lift<br><em>are not enough.</em>'),
 paras=[('CODEM loue des monte-meubles avec technicien aux particuliers et aux professionnels, à la demi-journée ou à la journée. Le monte-meubles facilite le passage du mobilier par une fenêtre en hauteur lorsque l’immeuble n’a pas d’ascenseur, lorsque celui-ci est trop petit ou lorsque les couloirs sont étroits.','CODEM hires out furniture lifts with an operator to households and businesses, by the half-day or day. A lift brings furniture through an upper-floor window when there is no lift, the lift is too small or corridors are narrow.'),('Canapés, armoires, pianos et autres objets encombrants peuvent ainsi être montés ou descendus avec un équipement adapté. La manipulation de l’engin est réalisée par un technicien spécialisé.','Sofas, wardrobes, pianos and other bulky items can be raised or lowered with suitable equipment, operated by a specialist technician.')],
 checks=[('Réduction des risques pour le mobilier et les parties communes','Less risk to furniture and shared areas'),('Solution pour particuliers et professionnels','For households and businesses'),('Étude du stationnement et des contraintes de rue','Parking and street constraints assessed')],
 steps_title=('Préparer l’intervention<br><em>du monte-meubles.</em>','Preparing the<br><em>furniture lift.</em>'),
 steps=[('Décrivez l’immeuble','Describe the building','Étage, ouvertures, façade et espace disponible devant l’immeuble.','Floor, openings, facade and space in front of the building.'),('Listez les objets concernés','List the items','Dimensions et poids approximatifs des meubles à monter ou descendre.','Approximate size and weight of the items to raise or lower.'),('CODEM confirme l’équipement et le créneau','CODEM confirms equipment and slot','Le conseiller valide la faisabilité, le stationnement et l’horaire d’intervention.','The adviser confirms feasibility, parking and timing.')],
 photo='monte-meubles'),
'piano':dict(
 ess=[('Papier bulle et couvertures','Bubble wrap and blankets'),('Bull-kraft et cartons double cannelure','Bubble kraft and double-wall boxes'),('Emballage sur mesure','Custom packing'),('Sanglage pendant le transport','Strapped down in transit')],
 eyebrow=('Biens précieux','Valuable items'),title=('Manutention délicate<br><em>et transport spécialisé.</em>','Careful handling<br><em>and specialist transport.</em>'),
 paras=[('CODEM assure la manutention délicate et le transport spécialisé de meubles de valeur, œuvres d’art, pianos et objets volumineux. Tableaux, statues, armoires, tables ou fauteuils sont préparés avant leur déplacement afin de limiter les risques de choc.','CODEM provides careful handling and specialist transport for valuable furniture, artwork, pianos and bulky items. Paintings, statues, wardrobes, tables and armchairs are prepared before moving to limit the risk of knocks.'),('Lorsque les couloirs, escaliers ou ascenseurs ne permettent pas le passage, un monte-meubles ou un monte-charge peut être prévu. Les biens sont ensuite entreposés et sanglés pendant le transport.','Where corridors, stairs or lifts are too tight, a furniture lift or goods hoist can be arranged. Items are then secured and strapped down during transport.')],
 checks=[('Prise en charge des objets fragiles, précieux ou lourds','Fragile, valuable or heavy items handled'),('Protections adaptées à la taille et à la nature du bien','Protection suited to size and type of item'),('Étude des accès et des moyens techniques','Access and equipment assessed')],
 steps_title=('Protéger chaque objet<br><em>avec le matériel adapté.</em>','Protecting each item<br><em>with the right materials.</em>'),
 steps=[('Identifier et mesurer','Identify and measure','Précisez la nature, les dimensions, la valeur et la fragilité de chaque objet.','Tell us the type, size, value and fragility of each item.'),('Choisir les protections','Choose protection','CODEM sélectionne les emballages et protections adaptés à la forme et aux matériaux.','CODEM selects packing and protection suited to shape and materials.'),('Organiser la manutention et le transport','Organise handling and transport','Les accès, le besoin d’un monte-meubles et le sanglage dans le véhicule sont étudiés avant l’intervention.','Access, the need for a lift and strapping in the vehicle are planned beforehand.')],
 photo='ancien-26'),
}

def v1_blocks(key):
 d=V1.get(key)
 if not d:return ''
 ess=''.join(f'<li><span class="ess-num">0{i+1}</span>{t(a,c)}</li>' for i,(a,c) in enumerate(d['ess']))
 paras=''.join(f'<p>{t(a,c)}</p>' for a,c in d['paras'])
 checks=''.join(f'<li>{t(a,c)}</li>' for a,c in d['checks'])
 st=''.join(f'<article class="reveal"><span class="number">0{i+1}</span><h3>{t(a,c)}</h3><p>{t(e,f)}</p></article>' for i,(a,c,e,f) in enumerate(d['steps']))
 q=f"{url('devis')}?service={PROJECT_OF[key]}"
 return f'''<section class="section band-ivory essentials-band"><div class="wrap">{eyebrow('L’essentiel','The essentials')}<ul class="essentials">{ess}</ul></div></section><section class="section band-sand"><div class="wrap split"><div>{eyebrow(*d['eyebrow'])}<h2>{t(*d['title'])}</h2><div class="image-wrap" style="height:320px">{b.img(d['photo'],label(key))}</div></div><div>{paras}<ul class="check-list light-list green-checks">{checks}</ul><div class="actions"><a class="btn btn-cta" href="{q}">{t('Décrire mon projet','Describe my project')}</a>{link('contact',t('Être rappelé','Request a callback'),'btn outline')}</div></div></div></section><section class="section band-glacier"><div class="wrap">{eyebrow('Comment ça se passe','How it works')}<h2>{t(*d['steps_title'])}</h2><div class="process" style="grid-template-columns:repeat(3,1fr)">{st}</div><div class="actions inset"><a class="btn btn-cta" href="{q}">{t('Commencer le devis','Start my quote')}</a></div></div></section>'''

# Grille des formules issue de la brochure CODEM (V1) — à confirmer par CODEM
FORMULES=['Self','Self plus','Confort','Confort plus','Grand Confort']
GRID=[('Emballage du non-fragile','Packing non-fragile items','CCCXX'),('Emballage du fragile','Packing fragile items','CCXXX'),('Démontage des meubles','Dismantling furniture','CXXXX'),('Protection et mise sous housse','Protection and covers','XXXXX'),('Fourniture des emballages','Packing materials supplied','??XXX'),('Manutention et transport','Handling and transport','XXXXX'),('Mise en place du mobilier','Placing furniture','CXXXX'),('Remontage des meubles','Reassembling furniture','CXXXX'),('Déballage du fragile','Unpacking fragile items','CCXXX'),('Déballage du non-fragile','Unpacking non-fragile items','CCCCX')]
def formules_table():
 cell=lambda c:{'X':f'<td class="yes"><span aria-hidden="true">✓</span> CODEM</td>','C':f'<td class="you">{t("Vous","You")}</td>','?':f'<td class="tbd">{t("À préciser","To confirm")}</td>'}[c]
 head=''.join(f'<th scope="col">{f}</th>' for f in FORMULES)
 rows=''.join(f'<tr><th scope="row">{t(a,c)}</th>'+''.join(cell(x) for x in code)+'</tr>' for a,c,code in GRID)
 return f'''<section class="section band-sand" id="comparatif"><div class="wrap">{eyebrow('Comparatif','Comparison')}<h2>{t('Qui prend en charge<br><em>chaque étape ?</em>','Who handles<br><em>each step?</em>')}</h2><div class="table-scroll inset"><table class="formules"><thead><tr><th scope="col">{t('Prestation','Service')}</th>{head}</tr></thead><tbody>{rows}</tbody></table></div><p class="fine-print">{t('Les débranchements électriques et les arrivées d’eau restent à la charge du client dans les cinq formules. Grille établie d’après la brochure CODEM ; le contenu exact de votre formule est confirmé dans le devis.','Disconnecting electrical appliances and water supplies remains the client’s responsibility in all five packages. Grid based on the CODEM brochure; the exact scope of your package is confirmed in your quote.')}</p><div class="actions inset"><a class="btn btn-cta" href="{url('devis')}?service=particulier">{t('Demander un devis','Get a quote')}</a>{link('contact',t('Être rappelé','Request a callback'),'btn outline')}</div></div></section>'''

def zones_steps():
 data=[('Décrivez votre trajet','Describe your route','Indiquez la commune et le pays de départ ainsi que la destination souhaitée.','Enter the town and country of departure and your destination.'),('Précisez les contraintes','Add constraints','Ajoutez la date, votre flexibilité et les principaux accès aux deux adresses.','Add the date, your flexibility and the main access details at both addresses.'),('CODEM confirme la faisabilité','CODEM confirms feasibility','Un conseiller vérifie la zone, les moyens à prévoir et vous recontacte avant toute proposition.','An adviser checks the area and resources, then gets back to you before any proposal.')]
 st=''.join(f'<article class="reveal"><span class="number">0{i+1}</span><h3>{t(a,c)}</h3><p>{t(e,f)}</p></article>' for i,(a,c,e,f) in enumerate(data))
 return f'<section class="section band-glacier"><div class="wrap">{eyebrow("Départs partout en France","Departures across France")}<h2>{t("Comment faire vérifier<br><em>votre trajet ?</em>","How to get<br><em>your route checked</em>")}</h2><div class="process" style="grid-template-columns:repeat(3,1fr)">{st}</div><div class="actions inset">{link("devis",t("Faire vérifier mon trajet","Check my route"),"btn btn-cta")}</div></div></section>'

def conseils_extra():
 return [('L’assurance de vos biens','Insuring your belongings','Demandez à CODEM quelles garanties couvrent le transport et dans quelles limites. Listez les objets de valeur et leur valeur estimée avant le devis : ils peuvent nécessiter une déclaration ou une protection particulière.','Ask CODEM which cover applies during transport and its limits. List valuable items and their estimated value before the quote: they may need to be declared or specially protected.'),('Les démarches à anticiper','Paperwork to plan ahead','Signalez votre changement d’adresse, transférez ou résiliez vos contrats d’énergie, d’internet et d’assurance habitation, et vérifiez auprès de la mairie si une autorisation de stationnement est nécessaire pour le camion.','Update your address, transfer or cancel energy, internet and home insurance contracts, and check with the town hall whether a parking permit is needed for the truck.'),('Partir à l’étranger','Moving abroad','Gardez vos papiers d’identité et documents importants avec vous, préparez un inventaire détaillé et renseignez-vous sur les formalités du pays de destination. CODEM précise avec vous les documents utiles au transport.','Keep identity papers and important documents with you, prepare a detailed inventory and check the destination country’s formalities. CODEM confirms the documents needed for transport with you.')]

def proof_page(key):
 from pages import crumb
 if key=='avis':
  intro=('Des avis vérifiables,<br><em>publiés avec leur source.</em>','Verifiable reviews,<br><em>published with their source.</em>');lead=('Chaque avis affiché sur ce site indiquera sa source, sa date et le prénom du client, avec son accord. Les avis des clients de CODEM y seront repris après vérification.','Every review shown here will state its source, date and the client’s first name, with their consent. CODEM client reviews will be added once verified.')
  items=[('Source identifiable','Identifiable source'),('Date visible','Visible date'),('Authenticité vérifiée','Verified authenticity'),('Droit de réponse','Right of reply')]
 else:
  intro=('Des déménagements réels,<br><em>racontés avec des faits.</em>','Real moves,<br><em>told with facts.</em>');lead=('Chaque réalisation présentera le besoin du client, les contraintes rencontrées, la solution mise en œuvre et des photos autorisées.','Each case study will show the client’s need, the constraints, the solution delivered and approved photos.')
  items=[('Besoin du client','Client need'),('Contraintes rencontrées','Constraints'),('Solution mise en œuvre','Solution delivered'),('Photos autorisées','Approved photos')]
 lis=''.join(f'<li><span class="ess-num">0{i+1}</span>{t(a,c)}</li>' for i,(a,c) in enumerate(items))
 return crumb(key)+f'<section class="page-title band-ivory"><div class="wrap">{eyebrow(*b.labels[key])}<h1>{t(*intro)}</h1><p class="lead">{t(*lead)}</p></div></section><section class="section band-sand"><div class="wrap"><ul class="essentials">{lis}</ul><p class="fine-print">{t("Contenus en cours de collecte auprès des clients de CODEM.","Content currently being collected from CODEM clients.")}</p></div></section>'+cta_strip('Votre projet sera peut-être notre prochaine réalisation.','Your move could be our next case study.')+b.cta()
